--USE Elit

/*Резервное копирование Alef_Elit
IF OBJECT_ID (N'_at_ALEF_AKCIA', N'U') IS NOT NULL DROP TABLE _at_ALEF_AKCIA
SELECT * into _at_ALEF_AKCIA FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA
IF OBJECT_ID (N'_at_ALEF_AKCIA_OBJECTS', N'U') IS NOT NULL DROP TABLE _at_ALEF_AKCIA_OBJECTS
SELECT * into _at_ALEF_AKCIA_OBJECTS FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS
IF OBJECT_ID (N'_at_ALEF_AKCIA_SUBJECTS', N'U') IS NOT NULL DROP TABLE _at_ALEF_AKCIA_SUBJECTS
SELECT * into _at_ALEF_AKCIA_SUBJECTS FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS
*/

--------------------------------------------------------------------------------
--Сравнить Акции в базе Elit и Alef_Elit
DECLARE @s varchar(max)
EXEC [ap_SyncAKCIA_ELIT_To_ALEF] @OnlyShow = 1, @OnlyRunID = NULL, @Revers = 0, @DifID = @s output
select @s 'ID по которым есть отличия'


--заменить акции в базе Alef_Elit на акцию из базы Elit
BEGIN TRAN

DECLARE @s varchar(max)
EXEC [ap_SyncAKCIA_ELIT_To_ALEF] @OnlyShow = 0, @OnlyRunID = NULL, @Revers = 0, @DifID = @s output
select @s 'ID по которым есть отличия'

ROLLBACK TRAN

--заменить акции в базе Elit на акцию из базы Alef_Elit
BEGIN TRAN

DECLARE @s varchar(max)
EXEC [ap_SyncAKCIA_ELIT_To_ALEF] @OnlyShow = 0, @OnlyRunID = NULL, @Revers = 1, @DifID = @s output
select @s 'ID по которым есть отличия'

ROLLBACK TRAN

--Копировать акцию в базе Elit
BEGIN TRAN

EXEC [dbo].[ap_Copy_ALEF_AKCIA] @ID = 0

ROLLBACK TRAN

/*
DECLARE @result NVARCHAR(MAX) 

SELECT @result = COALESCE(@result + ',', '') + CAST(q1.ID AS NVARCHAR) FROM (

SELECT q.AA_ID 'ID' FROM (
SELECT * FROM (
SELECT * FROM at_ALEF_AKCIA WITH (NOLOCK)
EXCEPT
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WITH (NOLOCK)
) s
UNION
SELECT * FROM ( 
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WITH (NOLOCK)
EXCEPT
SELECT * FROM at_ALEF_AKCIA WITH (NOLOCK)
) s
) q
UNION
SELECT DISTINCT q.AO_ID 'ID' FROM (
SELECT * FROM (
SELECT * FROM at_ALEF_AKCIA_OBJECTS WITH (NOLOCK)
EXCEPT
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WITH (NOLOCK)
)s
UNION
SELECT * FROM (
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WITH (NOLOCK)
EXCEPT
SELECT * FROM at_ALEF_AKCIA_OBJECTS WITH (NOLOCK)
)s
) q
UNION
SELECT DISTINCT q.AS_ID 'ID' FROM (
SELECT * FROM (
SELECT * FROM at_ALEF_AKCIA_SUBJECTS WITH (NOLOCK)
EXCEPT
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WITH (NOLOCK)
)s
UNION
SELECT * FROM (
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WITH (NOLOCK)
EXCEPT
SELECT * FROM at_ALEF_AKCIA_SUBJECTS WITH (NOLOCK)
)s
) q
																) q1
--SELECT @result 'ID по которым есть отличия'

IF OBJECT_ID (N'tempdb..#D', N'U') IS NOT NULL DROP TABLE #D
CREATE TABLE #D (result NVARCHAR(MAX))
INSERT #D --(1 число если дата запуска скрипта с 16 по 31 и    16 число прошлого месяца если дата запуска с 1 по 15 текущего месяца)
	SELECT @result
SELECT result 'ID по которым есть отличия' FROM #D 

*/

/*
-- Alef_Elit --> Elit
--------------------------------------------------------------------------------
--ЗАМЕНИТЬ АКЦИИ В БАЗЕ Elit на акцию из базы Alef_Elit
BEGIN TRAN;
SET NOCOUNT ON
--SET NOCOUNT Off
DECLARE @S varchar(max) = (SELECT result FROM #D)
--'
--1,2,3
--'
SELECT AValue FROM dbo.zf_FilterToTable(REPLACE(@S, char(13) + char(10), '')) ORDER BY 1
DECLARE @ID INT
DECLARE CUR CURSOR STATIC FOR
	SELECT AValue FROM dbo.zf_FilterToTable(REPLACE(@S, char(13) + char(10), '')) ORDER BY 1
OPEN CUR
FETCH NEXT FROM CUR INTO @ID
WHILE @@FETCH_STATUS = 0    		 
BEGIN

	print @ID

	DELETE at_ALEF_AKCIA WHERE AA_ID = @ID
	DELETE at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID
	DELETE at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

	INSERT INTO at_ALEF_AKCIA
	SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WHERE AA_ID = @ID

	INSERT INTO at_ALEF_AKCIA_OBJECTS
	SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID

	INSERT INTO at_ALEF_AKCIA_SUBJECTS
	SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

FETCH NEXT FROM CUR INTO @ID
END 
CLOSE CUR
DEALLOCATE CUR
SET NOCOUNT Off
ROLLBACK TRAN;
*/





/*
IF 1=0--заменить акции в базе Alef_Elit на акцию из базы Elit
BEGIN

-- Elit --> Alef_Elit
--------------------------------------------------------------------------------
--заменить акции в базе Alef_Elit на акцию из базы Elit
DECLARE @result NVARCHAR(MAX) 

SELECT @result = COALESCE(@result + ',', '') + CAST(q1.ID AS NVARCHAR) FROM (

SELECT q.AA_ID 'ID' FROM (
SELECT * FROM (
SELECT * FROM at_ALEF_AKCIA WITH (NOLOCK)
EXCEPT
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WITH (NOLOCK)
) s
UNION
SELECT * FROM ( 
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WITH (NOLOCK)
EXCEPT
SELECT * FROM at_ALEF_AKCIA WITH (NOLOCK)
) s
) q
UNION
SELECT DISTINCT q.AO_ID 'ID' FROM (
SELECT * FROM (
SELECT * FROM at_ALEF_AKCIA_OBJECTS WITH (NOLOCK)
EXCEPT
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WITH (NOLOCK)
)s
UNION
SELECT * FROM (
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WITH (NOLOCK)
EXCEPT
SELECT * FROM at_ALEF_AKCIA_OBJECTS WITH (NOLOCK)
)s
) q
UNION
SELECT DISTINCT q.AS_ID 'ID' FROM (
SELECT * FROM (
SELECT * FROM at_ALEF_AKCIA_SUBJECTS WITH (NOLOCK)
EXCEPT
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WITH (NOLOCK)
)s
UNION
SELECT * FROM (
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WITH (NOLOCK)
EXCEPT
SELECT * FROM at_ALEF_AKCIA_SUBJECTS WITH (NOLOCK)
)s
) q
																) q1
--SELECT @result 'ID по которым есть отличия'

IF OBJECT_ID (N'tempdb..#D', N'U') IS NOT NULL DROP TABLE #D
CREATE TABLE #D (result NVARCHAR(MAX))
INSERT #D --(1 число если дата запуска скрипта с 16 по 31 и    16 число прошлого месяца если дата запуска с 1 по 15 текущего месяца)
	SELECT @result
SELECT result 'ID по которым есть отличия' FROM #D 


SET NOCOUNT ON
--SET NOCOUNT Off
DECLARE @S varchar(max) = (SELECT result FROM #D)
--'
--1,2,3
--'
SELECT AValue FROM dbo.zf_FilterToTable(REPLACE(@S, char(13) + char(10), '')) ORDER BY 1
DECLARE @ID INT
DECLARE CUR CURSOR STATIC FOR
	SELECT AValue FROM dbo.zf_FilterToTable(REPLACE(@S, char(13) + char(10), '')) ORDER BY 1
OPEN CUR
FETCH NEXT FROM CUR INTO @ID
WHILE @@FETCH_STATUS = 0    		 
BEGIN

	print @ID

	DELETE [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WHERE AA_ID = @ID
	DELETE [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID
	DELETE [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

	INSERT INTO [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA
		SELECT * FROM at_ALEF_AKCIA WHERE AA_ID = @ID

	INSERT INTO [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS
		SELECT * FROM at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID

	INSERT INTO [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS
		SELECT * FROM at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

FETCH NEXT FROM CUR INTO @ID
END 
CLOSE CUR
DEALLOCATE CUR
PRINT 'Готово'
SET NOCOUNT Off
END
*/


/*
BEGIN TRAN;

-- Alef_Elit --> Elit
--------------------------------------------------------------------------------
DECLARE @ID INT
--заменить акцию в базе Elit на акцию из базы Alef_Elit
DECLARE @ID INT = 1

	SELECT * FROM  at_ALEF_AKCIA WHERE AA_ID = @ID
	SELECT * FROM  at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID ORDER BY AO_isASSORT,AO_CODE
	SELECT * FROM  at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID


	DELETE at_ALEF_AKCIA WHERE AA_ID = @ID
	DELETE at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID
	DELETE at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

	INSERT INTO at_ALEF_AKCIA
	SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WHERE AA_ID = @ID

	INSERT INTO at_ALEF_AKCIA_OBJECTS
	SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID

	INSERT INTO at_ALEF_AKCIA_SUBJECTS
	SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

	SELECT * FROM  at_ALEF_AKCIA WHERE AA_ID = @ID
	SELECT * FROM  at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID ORDER BY AO_isASSORT,AO_CODE
	SELECT * FROM  at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

ROLLBACK TRAN;
*/

/*
IF 1=0
BEGIN
BEGIN TRAN;


-- Elit --> Alef_Elit
--------------------------------------------------------------------------------
--заменить акцию в базе Alef_Elit на акцию из базы Elit

DECLARE @ID INT = 210

SELECT * FROM  [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WHERE AA_ID = @ID
SELECT * FROM  [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID ORDER BY AO_isASSORT,AO_CODE
SELECT * FROM  [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

DELETE [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WHERE AA_ID = @ID
DELETE [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID
DELETE [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

INSERT INTO [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA
SELECT * FROM at_ALEF_AKCIA WHERE AA_ID = @ID

INSERT INTO [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS
SELECT * FROM at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID

INSERT INTO [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS
SELECT * FROM at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

SELECT * FROM  [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WHERE AA_ID = @ID
SELECT * FROM  [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID ORDER BY AO_isASSORT,AO_CODE
SELECT * FROM  [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

ROLLBACK TRAN;	
END
*/



/*--удалить акцию
DECLARE @ID INT = 22222
	DELETE at_ALEF_AKCIA WHERE AA_ID = @ID
	DELETE at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID
	DELETE at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

--проверить записи без строки главной таблице at_ALEF_AKCIA
SELECT * FROM  at_ALEF_AKCIA_OBJECTS WHERE AO_ID not in (SELECT AA_ID FROM  at_ALEF_AKCIA)
SELECT * FROM  at_ALEF_AKCIA_SUBJECTS WHERE AS_ID not in (SELECT AA_ID FROM  at_ALEF_AKCIA)
*/


	DELETE at_ALEF_AKCIA WHERE AA_ID IN (0)
	DELETE at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID
	DELETE at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID


/*
BEGIN TRAN

--Копировать акцию в базе Elit

DECLARE @ID INT = 216
DECLARE @NEWID INT 

SELECT * FROM  at_ALEF_AKCIA WHERE AA_ID = @ID
SELECT * FROM  at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID ORDER BY AO_isASSORT,AO_CODE
SELECT * FROM  at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

SELECT isnull(max(AA_ID),0) + 1 'новый номер акции' FROM at_ALEF_AKCIA
SELECT @NEWID = isnull(max(AA_ID),0) + 1 FROM at_ALEF_AKCIA

INSERT INTO at_ALEF_AKCIA
	SELECT @NEWID AA_ID, 'Копия' + cast(@ID as varchar) + '=' + AA_NAME AA_NAME
	, AA_DATE_FROM, AA_DATE_TO
	, 'Копия' + cast(@ID as varchar) + '=' + AA_NOTE AA_NOTE, 0 AA_isACTIVE, AA_isPAYTYPE, AA_isSTOCKCHECK, AA_OVERALL, AA_MDCheck, AA_APCheck, AA_MAXQTY, AA_C1, AA_C2, AA_C3, AA_C4, AA_C5 
	FROM at_ALEF_AKCIA WHERE AA_ID = @ID

INSERT INTO at_ALEF_AKCIA_OBJECTS
	SELECT @NEWID AO_ID, AO_CODE, AO_QTY, AO_isASSORT, AO_isAltStock, AO_Tag, AO_Order
	FROM at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID

INSERT INTO at_ALEF_AKCIA_SUBJECTS
	SELECT @NEWID AS_ID, AS_CODES, AS_INCLUDE, AS_TYPE, AS_DATE_FROM, AS_DATE_TO 
	FROM at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

SELECT * FROM  at_ALEF_AKCIA WHERE AA_ID = @NEWID
SELECT * FROM  at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @NEWID ORDER BY AO_isASSORT,AO_CODE
SELECT * FROM  at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @NEWID

ROLLBACK TRAN
*/


DECLARE @ID INT = 22222

SELECT * FROM  at_ALEF_AKCIA WHERE AA_ID = @ID
SELECT * FROM  at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID ORDER BY AO_isASSORT,AO_CODE
SELECT * FROM  at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID



/*
DECLARE @AA_ID INT

DECLARE CURSOR1 CURSOR LOCAL FAST_FORWARD 
FOR 
SELECT AA_ID
FROM at_ALEF_AKCIA

OPEN CURSOR1
	FETCH NEXT FROM CURSOR1 INTO @AA_ID
WHILE @@FETCH_STATUS = 0	 
BEGIN
	
	IF EXISTS (
	SELECT 1
	FROM at_ALEF_AKCIA m
	JOIN [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA sppc WITH(NOLOCK) ON sppc.AA_ID = m.AA_ID
	WHERE m.AA_ID = @AA_ID AND 
		  (m.AA_NAME != sppc.AA_NAME
		   OR m.AA_NOTE != sppc.AA_NOTE
		  )
			   )
	BEGIN
		SELECT m.AA_NAME 'Name in Elit', sppc.AA_NAME 'Name on S-PPC', m.AA_NOTE 'Note on Elit', sppc.AA_NOTE 'Note on S-PPC'
		FROM at_ALEF_AKCIA m
		JOIN [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA sppc WITH(NOLOCK) ON sppc.AA_ID = m.AA_ID
		WHERE m.AA_ID = @AA_ID AND 
			  (m.AA_NAME != sppc.AA_NAME
			   OR m.AA_NOTE != sppc.AA_NOTE
			  )
	END;

		
	FETCH NEXT FROM CURSOR1 INTO @AA_ID
END
CLOSE CURSOR1
DEALLOCATE CURSOR1

SELECT
  p.ProdID, g.PGrName1, p.PGrID1
  ,ISNULL((SELECT top 1 CAST(Notes AS INT) FROM r_Uni WHERE RefTypeID = 80023 AND ISNUMERIC(Notes) = 1 AND RefID = (SELECT top 1 PGrID1 FROM r_Prods p2 where p2.ProdID = p.ProdID) ), 0) CodeID4
  ,CodeID5
FROM r_Prods p  WITH (NOLOCK)   
JOIN r_ProdG1 g WITH (NOLOCK) ON g.PGrID1 = p.PGrID1
ORDER BY PGrName1

SELECT
AA_ID, AA_NAME
FROM  at_ALEF_AKCIA WITH (NOLOCK) 
ORDER BY AA_ID


SELECT * FROM at_ALEF_AKCIA WHERE aa_id = 72
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WHERE aa_id = 72
*/


