SELECT * FROM [S-SQL-D4].[Elit].[dbo].at_t_IORec_— ORDER BY IOH_ADD_DATE DESC
SELECT * FROM [t_IORec] WHERE KursMC = 28 ORDER BY ChID DESC
SELECT m.OrderID, * FROM [t_IORec] m WHERE KursMC = 28 and DocDate >= '20210610' ORDER BY DocDate DESC

SELECT m.OrderID, * FROM [t_IORec] m WHERE KursMC = 28 and DocDate >= '20210610' and m.CompID in (SELECT RefID FROM r_Uni WHERE RefTypeID = 80019) ORDER BY DocDate DESC
--SELECT m.OrderID, * FROM [t_IORec] m WHERE KursMC = 29 and DocDate >= '20210610' and m.CompID in (SELECT RefID FROM r_Uni WHERE RefTypeID = 80019) ORDER BY DocDate DESC
SELECT m.OrderID, * FROM [at_t_IORes] m WHERE KursMC = 28 and DocDate >= '20210610' and m.CompID in (SELECT RefID FROM r_Uni WHERE RefTypeID = 80019) ORDER BY DocDate DESC

[ap_EDI_Importing_Orders_OT]   

--SELECT * FROM ALEF_EDI_ORDERS_CHANGES ORDER BY EOC_CH_DATE DESC
SELECT * FROM ALEF_EDI_ORDERS_CHANGES WHERE EOC_ORDER_ID = '1000096008'
SELECT * FROM ALEF_EDI_ORDERS_2 WHERE ZEO_ORDER_NUMBER in ('«ÍÁ/VN2-0028620')
SELECT * FROM ALEF_EDI_ORDERS_2_POS WHERE ZEP_ORDER_ID in ('1000096008')

SELECT * FROM ALEF_EDI_ORDERS_2 WHERE ZEO_ORDER_NUMBER in ('90059000001991', '«ÍÁ/VN2-0028620', '4516273323', '4516273314')
SELECT * FROM ALEF_EDI_ORDERS_2_POS WHERE ZEP_ORDER_ID in ('1000096008','1000096234','1000096239','1000096240')

--TRAN
BEGIN TRAN
    --SELECT count(*) from ALEF_EDI_ORDERS_CHANGES WHERE --(...)
    --SELECT * FROM ALEF_EDI_ORDERS_CHANGES WHERE  --(...)ORDER BY 1 DESC
    --    update ALEF_EDI_ORDERS_CHANGES/*...¬Õ»Ã¿“≈À‹ÕŒ!*/ set WHERE --(...)
    --SELECT * FROM ALEF_EDI_ORDERS_CHANGES WHERE  --(...) ORDER BY 1 DESC
    --SELECT count(*) from ALEF_EDI_ORDERS_CHANGES WHERE --(...)
DECLARE @order varchar(max) = '«ÍÁ/VN2-0028620'
DECLARE @ZEO_ORDER_ID varchar(max) = (SELECT ZEO_ORDER_ID FROM ALEF_EDI_ORDERS_2 WHERE ZEO_ORDER_NUMBER = @order)
SELECT * FROM ALEF_EDI_ORDERS_CHANGES WHERE EOC_ORDER_ID = @ZEO_ORDER_ID

INSERT INTO ALEF_EDI_ORDERS_CHANGES (EOC_ORDER_ID, EOC_CH_DATE,EOC_TYPE, EOC_POS, EOC_CH_DATA, EOC_COMMITTED, EOC_EMP)
VALUES (@ZEO_ORDER_ID, CURRENT_TIMESTAMP, 200, 0, 0, 0, 7277)

SELECT * FROM ALEF_EDI_ORDERS_CHANGES WHERE EOC_ORDER_ID = @ZEO_ORDER_ID
ROLLBACK TRAN