--https://www.sql.ru/articles/mssql/03101301usingsqlservermetadata.shtml
sp_help [iv_ComplexMenu]
SELECT * FROM INFORMATION_SCHEMA.TABLES
SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME like '%it_ComplexMenu%'
SELECT * FROM INFORMATION_SCHEMA.CHECK_CONSTRAINTS
SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE TABLE_NAME = 'r_prods'
SELECT * FROM INFORMATION_SCHEMA.PARAMETERS WHERE SPECIFIC_NAME = 'ap_EXITE_ExportDoc'
SELECT * FROM INFORMATION_SCHEMA.ROUTINE_COLUMNS
SELECT * FROM INFORMATION_SCHEMA.VIEW_TABLE_USAGE