ALTER TABLE dbo.T_rec DISABLE TRIGGER M1_T_rec
ALTER TABLE dbo.T_recD DISABLE TRIGGER M2_T_recD
ALTER TABLE dbo.T_Cret DISABLE TRIGGER M3_T_Cret
ALTER TABLE 	dbo.T_CretD DISABLE TRIGGER 	M4_T_CretD
ALTER TABLE 	dbo.T_ven  DISABLE TRIGGER M5_T_ven
ALTER TABLE 	dbo.T_venA DISABLE TRIGGER 	M6_T_venA	
ALTER TABLE 	dbo.T_venD  DISABLE TRIGGER  M7_T_venD
ALTER TABLE 	dbo.T_Exp  DISABLE TRIGGER M8_T_Exp
ALTER TABLE 	dbo.T_ExpD DISABLE TRIGGER M9_T_ExpD
ALTER TABLE 	dbo.T_Epp  DISABLE TRIGGER M10_T_Epp
ALTER TABLE 	dbo.T_EppD  DISABLE TRIGGER M11_T_EppD



