/*

--самые большие таблицы по занимаемому месту
Use ElitR_test_IM
TRUNCATE TABLE z_LogUpdate
TRUNCATE TABLE t_SRecD
TRUNCATE TABLE z_LogDelete
TRUNCATE TABLE t_SaleD
TRUNCATE TABLE z_LogCreate
TRUNCATE TABLE t_Sale
TRUNCATE TABLE z_LogDiscRec
TRUNCATE TABLE z_ReplicaIn
TRUNCATE TABLE t_MonRec
TRUNCATE TABLE t_PInP
TRUNCATE TABLE t_SRecA
TRUNCATE TABLE z_LogDiscExp
TRUNCATE TABLE t_RecD
TRUNCATE TABLE r_ProdMPCh
TRUNCATE TABLE z_LogState
TRUNCATE TABLE z_DocLinks
TRUNCATE TABLE t_VenA
TRUNCATE TABLE t_EOExpD
TRUNCATE TABLE z_ReplicaEvents
TRUNCATE TABLE t_SalePays


*/

/*

TRUNCATE TABLE __bTexp
TRUNCATE TABLE __clients
TRUNCATE TABLE __discsql
TRUNCATE TABLE __ppids
TRUNCATE TABLE __t_RetChIDs
TRUNCATE TABLE __t_VenD
TRUNCATE TABLE __z_ReplicaEvents
TRUNCATE TABLE __z_ReplicaIn
TRUNCATE TABLE __z_ReplicaOut
TRUNCATE TABLE _calc
TRUNCATE TABLE _CheckReplica
TRUNCATE TABLE _DateQty
TRUNCATE TABLE _eppd
TRUNCATE TABLE _Prods
TRUNCATE TABLE _ReplicaOut
TRUNCATE TABLE _saled
TRUNCATE TABLE _saled17
TRUNCATE TABLE _test
TRUNCATE TABLE _TRemD
TRUNCATE TABLE at_t_IORes
TRUNCATE TABLE at_t_IOResD

--TRUNCATE TABLE t_Acc

TRUNCATE TABLE t_AccD
TRUNCATE TABLE t_AccRoutes
TRUNCATE TABLE t_AccSpends
TRUNCATE TABLE t_Booking
TRUNCATE TABLE t_BookingD
TRUNCATE TABLE t_BookingTemp
TRUNCATE TABLE t_BookingTempD

--TRUNCATE TABLE t_Cos

TRUNCATE TABLE t_CosD
TRUNCATE TABLE t_CosSpends

--TRUNCATE TABLE t_CRet

TRUNCATE TABLE t_CRetD
TRUNCATE TABLE t_CRetRoutes
TRUNCATE TABLE t_CRetSpends
TRUNCATE TABLE t_CRRet
TRUNCATE TABLE t_CRRetD
TRUNCATE TABLE t_CRRetDLV
TRUNCATE TABLE t_CRRetPays
TRUNCATE TABLE t_Cst
TRUNCATE TABLE t_CstD
TRUNCATE TABLE t_CstRoutes
TRUNCATE TABLE t_CstSpends
TRUNCATE TABLE t_DeskRes
TRUNCATE TABLE t_DeskResD

--TRUNCATE TABLE t_Dis

TRUNCATE TABLE t_DisD
TRUNCATE TABLE t_DisDD
TRUNCATE TABLE t_DisRoutes
TRUNCATE TABLE t_DisSpends

--TRUNCATE TABLE t_EOExp

TRUNCATE TABLE t_EOExpD
TRUNCATE TABLE t_EOExpDD
TRUNCATE TABLE t_EOExpRoutes
TRUNCATE TABLE t_EOExpSpends

--TRUNCATE TABLE t_EORec

TRUNCATE TABLE t_EORecD
TRUNCATE TABLE t_EORecRoutes
TRUNCATE TABLE t_EORecSpends
TRUNCATE TABLE t_Epp
TRUNCATE TABLE t_EppD
TRUNCATE TABLE t_EppRoutes
TRUNCATE TABLE t_EppSpends
TRUNCATE TABLE t_Est
TRUNCATE TABLE t_EstD
TRUNCATE TABLE t_Exc
TRUNCATE TABLE t_ExcD
TRUNCATE TABLE t_ExcRoutes
TRUNCATE TABLE t_ExcSpends
TRUNCATE TABLE t_Exp
TRUNCATE TABLE t_ExpD
TRUNCATE TABLE t_ExpRoutes
TRUNCATE TABLE t_ExpSpends
TRUNCATE TABLE t_Inv
TRUNCATE TABLE t_InvD
TRUNCATE TABLE t_InvRoutes
TRUNCATE TABLE t_InvSpends

--TRUNCATE TABLE t_IOExp

TRUNCATE TABLE t_IOExpD
TRUNCATE TABLE t_IOExpRoutes
TRUNCATE TABLE t_IOExpSpends

--TRUNCATE TABLE t_IORec

TRUNCATE TABLE t_IORecD
TRUNCATE TABLE t_IORecRoutes
TRUNCATE TABLE t_IORecSpends
TRUNCATE TABLE t_MonIntExp
TRUNCATE TABLE t_MonIntRec
TRUNCATE TABLE t_MonRec
TRUNCATE TABLE t_PInP
TRUNCATE TABLE t_PInPCh
TRUNCATE TABLE t_Rec
TRUNCATE TABLE t_RecD
TRUNCATE TABLE t_RecRoutes
TRUNCATE TABLE t_RecSpends
TRUNCATE TABLE t_Rem
TRUNCATE TABLE t_RemD

--TRUNCATE TABLE t_RestShift 

TRUNCATE TABLE t_RestShiftD
TRUNCATE TABLE t_Ret
TRUNCATE TABLE t_RetD
TRUNCATE TABLE t_RetRoutes
TRUNCATE TABLE t_RetSpends
TRUNCATE TABLE t_Sale
TRUNCATE TABLE t_SaleC
TRUNCATE TABLE t_SaleD
TRUNCATE TABLE t_SaleDLV
TRUNCATE TABLE t_SalePays
TRUNCATE TABLE t_SaleTemp
TRUNCATE TABLE t_SaleTempD
TRUNCATE TABLE t_SaleTempM
TRUNCATE TABLE t_SaleTempPays
TRUNCATE TABLE t_SEst
TRUNCATE TABLE t_SEstD
TRUNCATE TABLE t_SExp
TRUNCATE TABLE t_SExpA
TRUNCATE TABLE t_SExpD
TRUNCATE TABLE t_SExpE
TRUNCATE TABLE t_SExpM
TRUNCATE TABLE t_SPExp
TRUNCATE TABLE t_SPExpA
TRUNCATE TABLE t_SPExpD
TRUNCATE TABLE t_SPExpE
TRUNCATE TABLE t_SPExpM
TRUNCATE TABLE t_SPRec
TRUNCATE TABLE t_SPRecA
TRUNCATE TABLE t_SPRecD
TRUNCATE TABLE t_SPRecE
TRUNCATE TABLE t_SPRecM
TRUNCATE TABLE t_SRec
TRUNCATE TABLE t_SRecA
TRUNCATE TABLE t_SRecD
TRUNCATE TABLE t_SRecE
TRUNCATE TABLE t_SRecM
TRUNCATE TABLE t_Ven
TRUNCATE TABLE t_VenA
TRUNCATE TABLE t_VenD
TRUNCATE TABLE t_VenD_UM
TRUNCATE TABLE t_VenRoutes
TRUNCATE TABLE t_VenSpends
TRUNCATE TABLE t_zInP
TRUNCATE TABLE t_zRep
TRUNCATE TABLE z_DocDC
TRUNCATE TABLE z_DocLinks
TRUNCATE TABLE z_LogCreate
TRUNCATE TABLE z_LogDelete
TRUNCATE TABLE z_LogDiscExp
TRUNCATE TABLE z_LogDiscRec
TRUNCATE TABLE z_LogState
TRUNCATE TABLE z_LogUpdate
TRUNCATE TABLE z_ReplicaConfigEvents
TRUNCATE TABLE z_ReplicaConfigOut
TRUNCATE TABLE z_ReplicaEvents
TRUNCATE TABLE z_ReplicaIn
TRUNCATE TABLE z_ReplicaOut


*/

/*
--Добавление нулевых партий
INSERT t_PInP
	SELECT * FROM [s-sql-d4].elitr.dbo.t_pinp where PPID = 0
*/