USE [Alef_Elit]
GO
/****** Object:  StoredProcedure [dbo].[ALEF_REPORT_ORDERS_GET_ID]    Script Date: 22.04.2019 11:00:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[ALEF_REPORT_ORDERS_GET_ID] @WARTOSC INT OUTPUT
AS
BEGIN
  if @@TRANCOUNT > 0
     SAVE TRANSACTION GET_ID_TRAN;
  ELSE
     BEGIN TRANSACTION GET_ID_TRAN;
  EXECUTE ('INSERT ALEF_ORDERS_REPORT_SEQ (NEXTVAL) VALUES (1)');
  SET @WARTOSC = @@IDENTITY;
  ROLLBACK TRANSACTION GET_ID_TRAN;
END

GO
