SELECT * FROM t_Inv
SELECT * FROM t_InvD ORDER BY 1 desc, 2

SELECT top 1000 * FROM (
SELECT   distinct (SELECT top 1 DocID FROM t_Inv i WHERE i.ChiD = s1.ChID) docid  FROM (
SELECT ChiD,SrcPosID, ROW_NUMBER()OVER(ORDER BY SrcPosID) N  FROM t_InvD ) s1
WHERE s1.SrcPosID <> s1.N)s2
ORDER BY 1 desc

SELECT *,(SELECT top 1 DocID FROM t_Inv i WHERE i.ChiD = s1.ChID) docid   FROM (
SELECT ChID, MAX(SrcPosID) m , COUNT(ChID) c FROM t_InvD 
group by ChID
having MAX(SrcPosID) <> COUNT(ChID)
)s1
ORDER BY 1 desc

SELECT * FROM t_Inv WHERE ChiD = 200134060
SELECT ChiD,SrcPosID, ROW_NUMBER()OVER(ORDER BY SrcPosID)  FROM t_InvD WHERE ChiD = 101314960
ORDER BY 1 


BEGIN TRAN


UPDATE s1
SET s1.SrcPosID = s1.N  
FROM (SELECT ChiD,SrcPosID, ROW_NUMBER()OVER(ORDER BY SrcPosID) N FROM t_InvD WHERE ChiD = 200134058) s1


SELECT ChiD,SrcPosID, ROW_NUMBER()OVER(ORDER BY SrcPosID) N  FROM t_InvD
WHERE ChiD = 200134058
ORDER BY 1

ROLLBACK TRAN
