--SET TRANSACTION ISOLATION LEVEL READ COMMITTED
--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
dbcc useroptions

setuser 'tester'
select SUSER_SNAME()

SET LOCK_TIMEOUT -1;
SELECT * FROM Loky --WITH(NOLOCK)
KILL 162
--select @@SPID


