CREATE EXTERNAL SCHEMA hcm_db
FROM DATA CATALOG
DATABASE 'hcm_db'  -- NAME OF THE GLUE CATALOG DATABASE
IAM_ROLE 'arn:aws:iam::370519913792:role/redshift-role'  --ARN OF THE REDSHIFT ROLE (should have glue, s3 permissions)
CREATE EXTERNAL DATABASE IF NOT EXISTS;
