--TRUNCATE TABLE at_r_Clients
--TRUNCATE TABLE at_r_ProdG4
--TRUNCATE TABLE at_r_ProdG5
--TRUNCATE TABLE at_r_ProdG6
--TRUNCATE TABLE at_r_ProdG7
--TRUNCATE TABLE at_r_ProdsAmort
--TRUNCATE TABLE at_r_Regions
--TRUNCATE TABLE b_GOperDocs
--TRUNCATE TABLE b_GView
--TRUNCATE TABLE b_TExp
--TRUNCATE TABLE ir_DCardsOld
--TRUNCATE TABLE ir_DeliveryGroup
--TRUNCATE TABLE ir_OperTypes
--TRUNCATE TABLE ir_PLProdGrs
--TRUNCATE TABLE ir_ProdOpers
--TRUNCATE TABLE ir_StockFilters
--TRUNCATE TABLE ir_StockSubs
--TRUNCATE TABLE it_CancPrice
--TRUNCATE TABLE it_CancPriceD
--TRUNCATE TABLE it_PrintPriceList
--TRUNCATE TABLE it_Spec
--TRUNCATE TABLE it_SpecD
--TRUNCATE TABLE it_SpecParams
--TRUNCATE TABLE p_CPIs
--TRUNCATE TABLE r_AssetC
--TRUNCATE TABLE r_AssetG
--TRUNCATE TABLE r_AssetG1
--TRUNCATE TABLE r_AssetGDeps
--TRUNCATE TABLE r_AssetH
--TRUNCATE TABLE r_Assets
--TRUNCATE TABLE r_Banks
--TRUNCATE TABLE r_Codes1
--TRUNCATE TABLE r_Codes2
--TRUNCATE TABLE r_Codes3
--TRUNCATE TABLE r_Codes4
--TRUNCATE TABLE r_Codes5
--TRUNCATE TABLE r_CompG
--TRUNCATE TABLE r_CompGrs1
--TRUNCATE TABLE r_CompGrs2
--TRUNCATE TABLE r_CompGrs3
--TRUNCATE TABLE r_CompGrs4
--TRUNCATE TABLE r_CompGrs5
--TRUNCATE TABLE r_CompMG
delete r_Comps
--TRUNCATE TABLE r_CompsAC
--TRUNCATE TABLE r_CompsAdd
--TRUNCATE TABLE r_CompsCC
--TRUNCATE TABLE r_CRDeskG
--TRUNCATE TABLE r_CRMP
--TRUNCATE TABLE r_CRPOSPays
delete r_CRs
--TRUNCATE TABLE r_CRSrvs
--TRUNCATE TABLE r_CRUniInput
--TRUNCATE TABLE r_CurrH
--TRUNCATE TABLE r_Currs
--TRUNCATE TABLE r_DBIs
--TRUNCATE TABLE r_DCards
--TRUNCATE TABLE r_DCTypeG
delete r_DCTypes
--TRUNCATE TABLE r_Deps
delete r_DeskG
--TRUNCATE TABLE r_Desks
--TRUNCATE TABLE r_DeviceTypes
--TRUNCATE TABLE r_DiscChargeD
--TRUNCATE TABLE r_DiscChargeDT
--TRUNCATE TABLE r_DiscDC
delete r_Discs
delete r_DiscSaleD
--TRUNCATE TABLE r_DiscSaleDBonus
--TRUNCATE TABLE r_DiscSaleDT
--TRUNCATE TABLE r_DiscSaleT
--TRUNCATE TABLE r_DocShed
--TRUNCATE TABLE r_Emps
--TRUNCATE TABLE r_Executors
--TRUNCATE TABLE r_GAccs
--TRUNCATE TABLE r_GAccs1
--TRUNCATE TABLE r_GAccs2
--TRUNCATE TABLE r_GOperC
--TRUNCATE TABLE r_GOperD
--TRUNCATE TABLE r_GOperFC
--TRUNCATE TABLE r_GOpers
--TRUNCATE TABLE r_GVols
--TRUNCATE TABLE r_Holidays
--TRUNCATE TABLE r_Levies
--TRUNCATE TABLE r_LevyCR
--TRUNCATE TABLE r_LevyRates
--TRUNCATE TABLE r_Mods
--TRUNCATE TABLE r_NormMH
--TRUNCATE TABLE r_Norms
--TRUNCATE TABLE r_OperCRs
--TRUNCATE TABLE r_Opers
--TRUNCATE TABLE r_Ours
--TRUNCATE TABLE r_OursAC
--TRUNCATE TABLE r_OursCC
--TRUNCATE TABLE r_PayForms
--TRUNCATE TABLE r_PayTypeCats
--TRUNCATE TABLE r_PayTypes
--TRUNCATE TABLE r_PCs
--TRUNCATE TABLE r_Persons
--TRUNCATE TABLE r_PLs
--TRUNCATE TABLE r_POSPays
--TRUNCATE TABLE r_PostC
--TRUNCATE TABLE r_PostMC
--TRUNCATE TABLE r_Posts
--TRUNCATE TABLE r_Prevs
--TRUNCATE TABLE r_Processings
--TRUNCATE TABLE r_ProdA
--TRUNCATE TABLE r_ProdBG
--TRUNCATE TABLE r_ProdC
--TRUNCATE TABLE r_ProdEC
--TRUNCATE TABLE r_ProdG
--TRUNCATE TABLE r_ProdG1
--TRUNCATE TABLE r_ProdG2
--TRUNCATE TABLE r_ProdG3
--TRUNCATE TABLE r_ProdLV
--TRUNCATE TABLE r_ProdMP
--TRUNCATE TABLE r_ProdMQ
--TRUNCATE TABLE r_ProdMS
--TRUNCATE TABLE r_ProdMSE
--TRUNCATE TABLE r_Prods
--TRUNCATE TABLE r_ProdValues
--TRUNCATE TABLE r_Resources
--TRUNCATE TABLE r_ResourceTypes
--TRUNCATE TABLE r_ScaleDefs
--TRUNCATE TABLE r_ScaleGrMW
--TRUNCATE TABLE r_ScaleGrs
--TRUNCATE TABLE r_Scales
--TRUNCATE TABLE r_Secs
--TRUNCATE TABLE r_Services
--TRUNCATE TABLE r_ShedMD
--TRUNCATE TABLE r_ShedMS
--TRUNCATE TABLE r_Sheds
--TRUNCATE TABLE r_Spends
--TRUNCATE TABLE r_StateDocs
--TRUNCATE TABLE r_StateDocsChange
--TRUNCATE TABLE r_StateRules
--TRUNCATE TABLE r_StateRuleUsers
--TRUNCATE TABLE r_States
--TRUNCATE TABLE r_StockCRProds
--TRUNCATE TABLE r_StockGs
--TRUNCATE TABLE r_Stocks
--TRUNCATE TABLE r_Subs
--TRUNCATE TABLE r_Taxes
--TRUNCATE TABLE r_TaxRates
--TRUNCATE TABLE r_TaxRegions
--TRUNCATE TABLE r_Uni
--TRUNCATE TABLE r_UniTypes
delete r_Users
--TRUNCATE TABLE r_WPrefs
--TRUNCATE TABLE r_WrkTypes
--TRUNCATE TABLE r_WTSigns
--TRUNCATE TABLE r_WWeeks
--TRUNCATE TABLE t_CRRet
--TRUNCATE TABLE t_CRRetD
--TRUNCATE TABLE t_CRRetDLV
--TRUNCATE TABLE t_CRRetPays
--TRUNCATE TABLE t_MonIntExp
--TRUNCATE TABLE t_MonIntRec
--TRUNCATE TABLE t_MonRec
--TRUNCATE TABLE t_PInP
--TRUNCATE TABLE t_Rem
delete t_RestShift
--TRUNCATE TABLE t_Sale
--TRUNCATE TABLE t_SaleC
--TRUNCATE TABLE t_SaleD
--TRUNCATE TABLE t_SaleDLV
--TRUNCATE TABLE t_SalePays
--TRUNCATE TABLE t_SaleTemp
--TRUNCATE TABLE t_VenD
--TRUNCATE TABLE t_zRep
delete v_Fields
--TRUNCATE TABLE v_Formulas
--TRUNCATE TABLE v_Graphs
--TRUNCATE TABLE v_MapSG
--TRUNCATE TABLE v_Params
delete v_RepGrs
--TRUNCATE TABLE v_Replace
delete v_Reps
--TRUNCATE TABLE v_RepUsers
--TRUNCATE TABLE v_Scripts
--TRUNCATE TABLE v_SourceGrs
delete v_Sources
--TRUNCATE TABLE v_Tables
--TRUNCATE TABLE v_UFields
--TRUNCATE TABLE v_UGraphs
--TRUNCATE TABLE v_UParams
--TRUNCATE TABLE v_UReps
--TRUNCATE TABLE v_UScripts
--TRUNCATE TABLE v_UViewFields
delete v_UViews
--TRUNCATE TABLE v_Valids
--TRUNCATE TABLE z_AccDefDocs
--TRUNCATE TABLE z_AccDefObjects
delete z_AccDefs
--TRUNCATE TABLE z_AccDefTables
--TRUNCATE TABLE z_AppDocs
--TRUNCATE TABLE z_AppPrints
delete z_Apps
--TRUNCATE TABLE z_AUFields
delete z_AUGroups
--TRUNCATE TABLE z_AUTables
delete z_AutoUpdate
--TRUNCATE TABLE z_AzRoleReps
--TRUNCATE TABLE z_AzRoles
--TRUNCATE TABLE z_AzRoleUsers
--TRUNCATE TABLE z_AzValids
--TRUNCATE TABLE z_BarMask
--TRUNCATE TABLE z_DatasetFields
--TRUNCATE TABLE z_DatasetLinks
--TRUNCATE TABLE z_DataSets
delete z_DocCats
--TRUNCATE TABLE z_DocDC
delete z_DocGrps
--TRUNCATE TABLE z_DocLinks
--TRUNCATE TABLE z_DocLinkTypes
--TRUNCATE TABLE z_DocPrints
delete z_Docs
--TRUNCATE TABLE z_Fields
delete z_FieldsRep
delete z_FieldsRepGrps
--TRUNCATE TABLE z_FRUDFR
--TRUNCATE TABLE z_FRUDFRD
--TRUNCATE TABLE z_FRUDFs
--TRUNCATE TABLE z_Licenses
--TRUNCATE TABLE z_LogAU
--TRUNCATE TABLE z_LogCreate
--TRUNCATE TABLE z_LogDelete
--TRUNCATE TABLE z_LogDiscExp
--TRUNCATE TABLE z_LogDiscRec
--TRUNCATE TABLE z_LogDiscRecTemp
--TRUNCATE TABLE z_LogScale
--TRUNCATE TABLE z_LogState
--TRUNCATE TABLE z_LogTools
--TRUNCATE TABLE z_LogUpdate
--TRUNCATE TABLE z_Lookups
delete z_MetricaEvents
delete z_Objects
delete z_Relations
--TRUNCATE TABLE z_ReplicaFields
--TRUNCATE TABLE z_ReplicaFilters
--TRUNCATE TABLE z_ReplicaIn
--TRUNCATE TABLE z_ReplicaPCs
delete z_ReplicaPubs
--TRUNCATE TABLE z_ReplicaSubs
--TRUNCATE TABLE z_ReplicaTables
--TRUNCATE TABLE z_RoleDocs
--TRUNCATE TABLE z_RoleObjects
--TRUNCATE TABLE z_Roles
--TRUNCATE TABLE z_RoleTables
--TRUNCATE TABLE z_RoleUsers
--TRUNCATE TABLE z_Tables
--TRUNCATE TABLE z_ToolApps
--TRUNCATE TABLE z_ToolDocs
--TRUNCATE TABLE z_ToolPages
--TRUNCATE TABLE z_ToolRep
--TRUNCATE TABLE z_Tools
--TRUNCATE TABLE z_ToolUserEvents
--TRUNCATE TABLE z_UserCodes3
--TRUNCATE TABLE z_UserCodes4
--TRUNCATE TABLE z_UserObjects
--TRUNCATE TABLE z_UserOurs
--TRUNCATE TABLE z_UserStockGs
--TRUNCATE TABLE z_UserStocks
--TRUNCATE TABLE z_UserVars
--TRUNCATE TABLE z_VarPages
--TRUNCATE TABLE z_Vars
TRUNCATE TABLE z_WCopy
TRUNCATE TABLE z_WCopyD
TRUNCATE TABLE z_WCopyDF
TRUNCATE TABLE z_WCopyDV
TRUNCATE TABLE z_WCopyF
TRUNCATE TABLE z_WCopyFUF
TRUNCATE TABLE z_WCopyFV
TRUNCATE TABLE z_WCopyFVUF
TRUNCATE TABLE z_WCopyP
TRUNCATE TABLE z_WCopyT
TRUNCATE TABLE z_WCopyU
TRUNCATE TABLE z_WCopyUV


DISABLE TRIGGER ALL ON r_CRs; delete  r_CRs; ENABLE  TRIGGER ALL ON r_CRs;
DISABLE TRIGGER ALL ON r_DCTypes; delete  r_DCTypes; ENABLE  TRIGGER ALL ON r_DCTypes;
DISABLE TRIGGER ALL ON r_DeskG; delete  r_DeskG; ENABLE  TRIGGER ALL ON r_DeskG;
DISABLE TRIGGER ALL ON r_Discs; delete  r_Discs; ENABLE  TRIGGER ALL ON r_Discs;
DISABLE TRIGGER ALL ON r_DiscSaleD; delete  r_DiscSaleD; ENABLE  TRIGGER ALL ON r_DiscSaleD;
DISABLE TRIGGER ALL ON r_Users; delete  r_Users; ENABLE  TRIGGER ALL ON r_Users;
DISABLE TRIGGER ALL ON t_RestShift; delete  t_RestShift; ENABLE  TRIGGER ALL ON t_RestShift;
DISABLE TRIGGER ALL ON v_Fields; delete  v_Fields; ENABLE  TRIGGER ALL ON v_Fields;
DISABLE TRIGGER ALL ON v_RepGrs; delete  v_RepGrs; ENABLE  TRIGGER ALL ON v_RepGrs;
DISABLE TRIGGER ALL ON v_Reps; delete  v_Reps; ENABLE  TRIGGER ALL ON v_Reps;
DISABLE TRIGGER ALL ON v_Sources; delete  v_Sources; ENABLE  TRIGGER ALL ON v_Sources;
DISABLE TRIGGER ALL ON v_UViews; delete  v_UViews; ENABLE  TRIGGER ALL ON v_UViews;
DISABLE TRIGGER ALL ON z_AccDefs; delete  z_AccDefs; ENABLE  TRIGGER ALL ON z_AccDefs;
DISABLE TRIGGER ALL ON z_Apps; delete  z_Apps; ENABLE  TRIGGER ALL ON z_Apps;
--DISABLE TRIGGER ALL ON z_AUGroups; delete  z_AUGroups; ENABLE  TRIGGER ALL ON z_AUGroups;
DISABLE TRIGGER ALL ON z_AutoUpdate; delete  z_AutoUpdate; ENABLE  TRIGGER ALL ON z_AutoUpdate;
--DISABLE TRIGGER ALL ON z_DocCats; delete  z_DocCats; ENABLE  TRIGGER ALL ON z_DocCats;
--DISABLE TRIGGER ALL ON z_DocGrps; delete  z_DocGrps; ENABLE  TRIGGER ALL ON z_DocGrps;
--DISABLE TRIGGER ALL ON z_Docs; delete  z_Docs; ENABLE  TRIGGER ALL ON z_Docs;
DISABLE TRIGGER ALL ON z_FieldsRep; delete  z_FieldsRep; ENABLE  TRIGGER ALL ON z_FieldsRep;
DISABLE TRIGGER ALL ON z_FieldsRepGrps; delete  z_FieldsRepGrps; ENABLE  TRIGGER ALL ON z_FieldsRepGrps;
DISABLE TRIGGER ALL ON z_MetricaEvents; delete  z_MetricaEvents; ENABLE  TRIGGER ALL ON z_MetricaEvents;
DISABLE TRIGGER ALL ON z_Objects; delete  z_Objects; ENABLE  TRIGGER ALL ON z_Objects;
--DISABLE TRIGGER ALL ON z_Relations; delete  z_Relations; ENABLE  TRIGGER ALL ON z_Relations;
--DISABLE TRIGGER ALL ON z_ReplicaPubs; delete  z_ReplicaPubs; ENABLE  TRIGGER ALL ON z_ReplicaPubs;
DISABLE TRIGGER ALL ON z_Docs; delete  z_Docs; ENABLE  TRIGGER ALL ON z_Docs;

DISABLE TRIGGER ALL ON z_DocCats; delete  z_DocCats; ENABLE  TRIGGER ALL ON z_DocCats;
DISABLE TRIGGER ALL ON z_DocGrps; delete  z_DocGrps; ENABLE  TRIGGER ALL ON z_DocGrps;

DISABLE TRIGGER ALL ON z_ReplicaPubs; delete  z_ReplicaPubs; ENABLE  TRIGGER ALL ON z_ReplicaPubs;

