BEGIN TRAN;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_CRRetDLV; insert ElitR_306.dbo.t_CRRetDLV	(	ChID,SrcPosID,LevyID,LevySum	) select 	ChID,SrcPosID,LevyID,LevySum	from ElitR_316.dbo.t_CRRetDLV;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_CRRetDLV;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_CRRet; insert ElitR_306.dbo.t_CRRet	(	ChID,DocID,IntDocID,DocDate,KursMC,OurID,StockID,CompID,CRID,OperID,CodeID1,CodeID2,CodeID3,CodeID4,CodeID5,EmpID,Notes,Discount,CreditID,DCardID,SrcDocID,SrcDocDate,CurrID,TSumCC_nt,TTaxSum,TSumCC_wt,StateCode,DocTime,TaxDocID,TaxDocDate,DepID,ClientID,InDocID,DeclNum,DeclDate,DeskCode,BLineID,TRealSum,TLevySum,RemSChId	) select 	ChID, DocID, IntDocID, DocDate, KursMC, OurID, StockID, CompID, CRID, OperID, CodeID1, CodeID2, CodeID3, CodeID4, CodeID5, EmpID, Notes, Discount, CreditID, ISNULL(DCardID,'<Нет дисконтной карты>'), SrcDocID, SrcDocDate, CurrID, TSumCC_nt, TTaxSum, TSumCC_wt, StateCode, DocTime, TaxDocID, TaxDocDate, DepID, ClientID, InDocID, DeclNum, DeclDate, DeskCode, BLineID, TRealSum, TLevySum, RemSChId	from ElitR_316.dbo.t_CRRet;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_CRRet;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_CRRetD; insert ElitR_306.dbo.t_CRRetD	(	ChID,SrcPosID,ProdID,PPID,UM,Qty,PriceCC_nt,SumCC_nt,Tax,TaxSum,PriceCC_wt,SumCC_wt,BarCode,SecID,SaleSrcPosID,EmpID,CreateTime,ModifyTime,TaxTypeID,RealPrice,RealSum	) select 	ChID,SrcPosID,ProdID,PPID,UM,Qty,PriceCC_nt,SumCC_nt,Tax,TaxSum,PriceCC_wt,SumCC_wt,BarCode,SecID,SaleSrcPosID,EmpID,CreateTime,ModifyTime,TaxTypeID,RealPrice,RealSum	from ElitR_316.dbo.t_CRRetD;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_CRRetD;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_CRRetPays; insert ElitR_306.dbo.t_CRRetPays	(	ChID,SrcPosID,PayFormCode,SumCC_wt,Notes,POSPayID,SrcPayPosID,POSPayDocID,POSPayRRN	) select 	ChID,SrcPosID,PayFormCode,SumCC_wt,Notes,POSPayID,SrcPayPosID,POSPayDocID,POSPayRRN	from ElitR_316.dbo.t_CRRetPays;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_CRRetPays;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_MonIntExp; insert ElitR_306.dbo.t_MonIntExp	(	ChID,OurID,CRID,DocDate,DocTime,CodeID1,CodeID2,CodeID3,CodeID4,CodeID5,SumCC,Notes,OperID,StateCode,DocID,IntDocID	) select 	ChID,OurID,CRID,DocDate,DocTime,CodeID1,CodeID2,CodeID3,CodeID4,CodeID5,SumCC,Notes,OperID,StateCode,DocID,IntDocID	from ElitR_316.dbo.t_MonIntExp;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_MonIntExp;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_MonIntRec; insert ElitR_306.dbo.t_MonIntRec	(	ChID,OurID,CRID,DocDate,DocTime,CodeID1,CodeID2,CodeID3,CodeID4,CodeID5,SumCC,Notes,OperID,StateCode,DocID,IntDocID	) select 	ChID,OurID,CRID,DocDate,DocTime,CodeID1,CodeID2,CodeID3,CodeID4,CodeID5,SumCC,Notes,OperID,StateCode,DocID,IntDocID	from ElitR_316.dbo.t_MonIntRec;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_MonIntRec;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_MonRec; insert ElitR_306.dbo.t_MonRec	(	ChID,OurID,AccountAC,DocDate,DocID,StockID,CompID,CompAccountAC,CurrID,KursMC,KursCC,SumAC,Subject,CodeID1,CodeID2,CodeID3,CodeID4,CodeID5,EmpID,StateCode,DepID	) select 	ChID,OurID,AccountAC,DocDate,DocID,StockID,CompID,CompAccountAC,CurrID,KursMC,KursCC,SumAC,Subject,CodeID1,CodeID2,CodeID3,CodeID4,CodeID5,EmpID,StateCode,DepID	from ElitR_316.dbo.t_MonRec;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_MonRec;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_Sale; insert ElitR_306.dbo.t_Sale	(	ChID,DocID,DocDate,KursMC,OurID,StockID,CompID,CodeID1,CodeID2,CodeID3,CodeID4,CodeID5,Discount,Notes,CRID,OperID,CreditID,DocTime,TaxDocID,TaxDocDate,DCardID,EmpID,IntDocID,CashSumCC,ChangeSumCC,CurrID,TSumCC_nt,TTaxSum,TSumCC_wt,StateCode,DeskCode,Visitors,TPurSumCC_nt,TPurTaxSum,TPurSumCC_wt,DocCreateTime,DepID,ClientID,InDocID,ExpTime,DeclNum,DeclDate,BLineID,TRealSum,TLevySum,RemSChId	) select 	ChID,DocID,DocDate,KursMC,OurID,StockID,CompID,CodeID1,CodeID2,CodeID3,CodeID4,CodeID5,Discount,Notes,CRID,OperID,CreditID,DocTime,TaxDocID,TaxDocDate,DCardID,EmpID,IntDocID,CashSumCC,ChangeSumCC,CurrID,TSumCC_nt,TTaxSum,TSumCC_wt,StateCode,DeskCode,Visitors,TPurSumCC_nt,TPurTaxSum,TPurSumCC_wt,DocCreateTime,DepID,ClientID,InDocID,ExpTime,DeclNum,DeclDate,BLineID,TRealSum,TLevySum,RemSChId	from ElitR_316.dbo.t_Sale;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_Sale;

--8 done

DISABLE TRIGGER ALL ON ElitR_306.dbo.t_SaleC; insert ElitR_306.dbo.t_SaleC	(	ChID,SrcPosID,ProdID,UM,Qty,PriceCC_nt,SumCC_nt,Tax,TaxSum,PriceCC_wt,SumCC_wt,BarCode,CReasonID,EmpID,CreateTime,ModifyTime	) select 	ChID,SrcPosID,ProdID,UM,Qty,PriceCC_nt,SumCC_nt,Tax,TaxSum,PriceCC_wt,SumCC_wt,BarCode,CReasonID,EmpID,CreateTime,ModifyTime	from ElitR_316.dbo.t_SaleC;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_SaleC;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_SaleD; insert ElitR_306.dbo.t_SaleD	(	ChID,SrcPosID,ProdID,PPID,UM,Qty,PriceCC_nt,SumCC_nt,Tax,TaxSum,PriceCC_wt,SumCC_wt,BarCode,SecID,PurPriceCC_nt,PurTax,PurPriceCC_wt,PLID,Discount,DepID,IsFiscal,SubStockID,OutQty,EmpID,CreateTime,ModifyTime,TaxTypeID,RealPrice,RealSum	) select 	ChID,SrcPosID,ProdID,PPID,UM,Qty,PriceCC_nt,SumCC_nt,Tax,TaxSum,PriceCC_wt,SumCC_wt,BarCode,SecID,PurPriceCC_nt,PurTax,PurPriceCC_wt,PLID,Discount,DepID,IsFiscal,SubStockID,OutQty,EmpID,CreateTime,ModifyTime,TaxTypeID,RealPrice,RealSum	from ElitR_316.dbo.t_SaleD;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_SaleD;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_SaleDLV; insert ElitR_306.dbo.t_SaleDLV	(	ChID,SrcPosID,LevyID,LevySum	) select 	ChID,SrcPosID,LevyID,LevySum	from ElitR_316.dbo.t_SaleDLV;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_SaleDLV;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_SalePays; insert ElitR_306.dbo.t_SalePays	(	ChID,SrcPosID,PayFormCode,SumCC_wt,Notes,POSPayID,POSPayDocID,POSPayRRN,IsFiscal	) select 	ChID,SrcPosID,PayFormCode,SumCC_wt,Notes,POSPayID,POSPayDocID,POSPayRRN,IsFiscal	from ElitR_316.dbo.t_SalePays;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_SalePays;
DISABLE TRIGGER ALL ON ElitR_306.dbo.t_zRep; insert ElitR_306.dbo.t_zRep	(	ChID,DocDate,DocTime,CRID,OperID,OurID,DocID,FacID,FinID,ZRepNum,SumCC_wt,Sum_A,Sum_B,Sum_C,Sum_D,RetSum_A,RetSum_B,RetSum_C,RetSum_D,SumCash,SumCard,SumCredit,SumCheque,SumOther,RetSumCash,RetSumCard,RetSumCredit,RetSumCheque,RetSumOther,SumMonRec,SumMonExp,SumRem,Notes,Sum_E,Sum_F,RetSum_E,RetSum_F,Tax_A,Tax_B,Tax_C,Tax_D,Tax_E,Tax_F,RetTax_A,RetTax_B,RetTax_C,RetTax_D,RetTax_E,RetTax_F	) select 	ChID,DocDate,DocTime,CRID,OperID,OurID,DocID,FacID,FinID,ZRepNum,SumCC_wt,Sum_A,Sum_B,Sum_C,Sum_D,RetSum_A,RetSum_B,RetSum_C,RetSum_D,SumCash,SumCard,SumCredit,SumCheque,SumOther,RetSumCash,RetSumCard,RetSumCredit,RetSumCheque,RetSumOther,SumMonRec,SumMonExp,SumRem,Notes,Sum_E,Sum_F,RetSum_E,RetSum_F,Tax_A,Tax_B,Tax_C,Tax_D,Tax_E,Tax_F,RetTax_A,RetTax_B,RetTax_C,RetTax_D,RetTax_E,RetTax_F	from ElitR_316.dbo.t_zRep;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.t_zRep;
DISABLE TRIGGER ALL ON ElitR_306.dbo.z_DocDC; insert ElitR_306.dbo.z_DocDC	(	DocCode,ChID,DCardID	) select 	DocCode,ChID,DCardChID	from ElitR_316.dbo.z_DocDC;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.z_DocDC;

ALTER TABLE [dbo].[z_LogDiscRec]  NOCHECK  CONSTRAINT [FK_z_LogDiscRec_r_Discs];
ALTER TABLE [dbo].[z_LogDiscExp]  NOCHECK  CONSTRAINT [FK_z_LogDiscExp_r_Discs];

DISABLE TRIGGER ALL ON ElitR_306.dbo.z_LogDiscExp; insert ElitR_306.dbo.z_LogDiscExp	(	LogID,DCardID,TempBonus,DocCode,ChID,SrcPosID,DiscCode,SumBonus,Discount,LogDate,BonusType,GroupSumBonus,GroupDiscount,DBiID	) select 	LogID,DCardChID DCardID,TempBonus,DocCode,ChID,SrcPosID,DiscCode,SumBonus,Discount,LogDate,BonusType,GroupSumBonus,GroupDiscount,DBiID	from ElitR_316.dbo.z_LogDiscExp;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.z_LogDiscExp;
DISABLE TRIGGER ALL ON ElitR_306.dbo.z_LogDiscRec; insert ElitR_306.dbo.z_LogDiscRec	(	LogID,DCardID,TempBonus,DocCode,ChID,SrcPosID,DiscCode,SumBonus,LogDate,BonusType,SaleSrcPosID,DBiID	) select 	LogID,DCardChID DCardID,TempBonus,DocCode,ChID,SrcPosID,DiscCode,SumBonus,LogDate,BonusType,SaleSrcPosID,DBiID	from ElitR_316.dbo.z_LogDiscRec;	ENABLE  TRIGGER ALL ON ElitR_306.dbo.z_LogDiscRec;

ALTER TABLE [dbo].[z_LogDiscRec]  CHECK  CONSTRAINT [FK_z_LogDiscRec_r_Discs];
ALTER TABLE [dbo].[z_LogDiscExp]  CHECK  CONSTRAINT [FK_z_LogDiscExp_r_Discs];
ROLLBACK TRAN;