DECLARE @result NVARCHAR(max) 

SELECT @result = COALESCE(@result + ',', '') + CAST(q1.ID AS NVARCHAR) FROM (

SELECT q.AA_ID 'ID' FROM (
SELECT * FROM at_ALEF_AKCIA
EXCEPT
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA
UNION
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA
EXCEPT
SELECT * FROM at_ALEF_AKCIA
) q
UNION
SELECT DISTINCT q.AO_ID 'ID' FROM (
SELECT * FROM at_ALEF_AKCIA_OBJECTS
EXCEPT
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS
UNION
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS
EXCEPT
SELECT * FROM at_ALEF_AKCIA_OBJECTS
) q
UNION
SELECT DISTINCT q.AS_ID 'ID' FROM (
SELECT * FROM at_ALEF_AKCIA_SUBJECTS
EXCEPT
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS
UNION
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS
EXCEPT
SELECT * FROM at_ALEF_AKCIA_SUBJECTS
) q
																) q1
SELECT @result 'ID'

DECLARE @ID INT = 1

BEGIN TRAN;

--DELETE [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WHERE AA_ID = @ID
--DELETE [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID
--DELETE [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID
SELECT * FROM at_ALEF_AKCIA WHERE AA_ID = @ID

DELETE at_ALEF_AKCIA WHERE AA_ID = @ID
DELETE at_ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID
DELETE at_ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

INSERT INTO at_ALEF_AKCIA
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WHERE AA_ID = @ID

INSERT INTO at_ALEF_AKCIA_OBJECTS
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_OBJECTS WHERE AO_ID = @ID

INSERT INTO at_ALEF_AKCIA_SUBJECTS
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA_SUBJECTS WHERE AS_ID = @ID

SELECT * FROM at_ALEF_AKCIA WHERE AA_ID = @ID

ROLLBACK TRAN;
/*
DECLARE @AA_ID INT

DECLARE CURSOR1 CURSOR LOCAL FAST_FORWARD 
FOR 
SELECT AA_ID
FROM at_ALEF_AKCIA

OPEN CURSOR1
	FETCH NEXT FROM CURSOR1 INTO @AA_ID
WHILE @@FETCH_STATUS = 0	 
BEGIN
	
	IF EXISTS (
	SELECT 1
	FROM at_ALEF_AKCIA m
	JOIN [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA sppc WITH(NOLOCK) ON sppc.AA_ID = m.AA_ID
	WHERE m.AA_ID = @AA_ID AND 
		  (m.AA_NAME != sppc.AA_NAME
		   OR m.AA_NOTE != sppc.AA_NOTE
		  )
			   )
	BEGIN
		SELECT m.AA_NAME 'Name in Elit', sppc.AA_NAME 'Name on S-PPC', m.AA_NOTE 'Note on Elit', sppc.AA_NOTE 'Note on S-PPC'
		FROM at_ALEF_AKCIA m
		JOIN [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA sppc WITH(NOLOCK) ON sppc.AA_ID = m.AA_ID
		WHERE m.AA_ID = @AA_ID AND 
			  (m.AA_NAME != sppc.AA_NAME
			   OR m.AA_NOTE != sppc.AA_NOTE
			  )
	END;

		
	FETCH NEXT FROM CURSOR1 INTO @AA_ID
END
CLOSE CURSOR1
DEALLOCATE CURSOR1




SELECT * FROM at_ALEF_AKCIA WHERE aa_id = 72
SELECT * FROM [S-PPC.CONST.ALEF.UA].[Alef_Elit].[dbo].ALEF_AKCIA WHERE aa_id = 72
*/