USE OTData

SET NOCOUNT ON

/*PRINT '	- Очистка таблицы t_ZinP'
TRUNCATE TABLE t_ZinP

PRINT '	- Перенос текущих остатков во временную таблицу'
SELECT
IDENTITY (INT,1,1) ChID,
r.OurID,
r.StockID,
r.ProdID,
r.PPID,
r.SecID,
r.QTy,
t.PriceMC_In/1.2 AS PriceCC_nt,
t.PriceMC_In/1.2*r.QTy AS SumCC_nt,
t.PriceMC_In-t.PriceMC_In/1.2 AS Tax,
(t.PriceMC_In-t.PriceMC_In/1.2)*r.QTy AS TaxSum,
t.PriceMC_In AS PriceCC_wt,
t.PriceMC_In*r.QTy AS SumCC_wt,
1 AS KursMC,
0 AS CodeID1,
0 AS CodeID2,
0 AS CodeID3,
0 AS CodeID4,
0 AS CodeID5,
'Входящие остатки' AS Notes
INTO _Temp_t_ZinP
FROM t_PInP t
INNER JOIN t_Rem r ON t.PPID=r.PPID
WHERE t.ProdID=r.ProdID AND r.QTy<>0 

PRINT '	- Очистка таблицы t_ZinP'
TRUNCATE TABLE t_ZinP

PRINT '	- Перенос входящих остатков в таблицу t_ZinP'
DECLARE @I INT ,
	@X INT	
SELECT @I = MAX (ChID)
FROM _Temp_t_ZinP
SET  @X = 1
WHILE @X <= @I
BEGIN 
INSERT INTO t_ZinP 
SELECT *
FROM _Temp_t_ZinP
WHERE _Temp_t_ZinP.ChID = @X
SET @X = @X+1
END
*/
PRINT '	- Перенос нулевых партий во временную таблицу'
SELECT *
INTO _Temp_t_PinP
FROM t_PinP
WHERE PPID=0
/*
PRINT '	- Перенос значащих партий во временную таблицу'
INSERT INTO _Temp_t_PinP
SELECT t.*
FROM t_PInP t
INNER JOIN t_Rem z ON t.PPID=z.PPID
WHERE t.ProdID=z.ProdID and z.QTy<>0 and z.PPID>0
GROUP BY t.ProdID, t.PPID, t.PPDesc, t.PriceMC_In, t.PriceMC, t.Priority, t.ProdDate, t.CurrID, t.CompID, t.Article, t.CostAC, t.PPWeight, t.File1, t.File2, t.File3, t.PriceCC_In, t.CostCC, t.PPDelay, t.ProdPPDate
*/
PRINT '	- Очистка таблицы t_PinP'
TRUNCATE TABLE t_PinP
TRUNCATE TABLE t_PinP_T

PRINT '	- Перенос партий в таблицу t_PinP'
INSERT INTO t_PinP
SELECT *
FROM _Temp_t_PInP
INSERT INTO t_PinP_T
SELECT ProdID, PPID
FROM _Temp_t_PInP
/*
PRINT 'Обновление описания партий'
UPDATE t_PInP
SET PPDesc = 'Входящие остатки'
WHERE PPID>0
*/
UPDATE t_PInP
SET PPDesc = 'Системная партия',
PriceMC_In=0,
PriceMC = 0,
Priority = 0,
ProdDate = '1900-01-01 00:00:00.000',
CurrID = 980,
CompID = 0,
Article = '',
CostAC = 0,
PPWeight = 0,
PriceCC_In = 0,
CostCC = 0,
PPDelay = 0,
ProdPPDate = '1900-01-01 00:00:00.000'
WHERE PPID=0

PRINT '	Удаление документов'

TRUNCATE TABLE t_Acc
TRUNCATE TABLE t_AccD
PRINT '	- Удаление документа СЧЁТ НА ОПЛАТУ ТОВАРА МАГАЗИНА'

TRUNCATE TABLE t_Rec
TRUNCATE TABLE t_RecD
PRINT '	- Удаление документа ПРИХОД В МАГАЗИН'

TRUNCATE TABLE t_CRRet
TRUNCATE TABLE t_CRRetD
PRINT '	- Удаление документа ВОЗВРАТ В МАГАЗИН'

TRUNCATE TABLE t_Ret
TRUNCATE TABLE t_RetD
PRINT '	- Удаление документа БЕЗНАЛИЧНЫЙ ВОЗВРАТ В МАГАЗИН'

TRUNCATE TABLE t_Exp
TRUNCATE TABLE t_ExpD
PRINT '	- Удаление документа РАСХОД МАГАЗИНА'

TRUNCATE TABLE t_Sale
TRUNCATE TABLE t_SaleC
TRUNCATE TABLE t_SaleD
PRINT '	- Удаление документа ПРОДАЖА ТОВАРА'

TRUNCATE TABLE t_CRSale
TRUNCATE TABLE t_CRSaleD
PRINT '	- Удаление документа ПРОДАЖА ЧЕРЕЗ ТОРГОВЫЙ СЕРВЕР'

TRUNCATE TABLE t_Epp
TRUNCATE TABLE t_EppD
PRINT '	- Удаление документа РАСХОД МАГАЗИНА В ЦЕНАХ ПРИХОДА'

TRUNCATE TABLE t_CRet
TRUNCATE TABLE t_CRetD
PRINT '	- Удаление документа ВОЗВРАТ МАГАЗИНА ПОСТАВЩИКУ'

TRUNCATE TABLE t_Exc
TRUNCATE TABLE t_ExcD
PRINT '	- Удаление документа ПЕРЕМЕЩЕНИЕ В МАГАЗИНЕ'

TRUNCATE TABLE t_Ven
TRUNCATE TABLE t_VenA
TRUNCATE TABLE t_VenD
PRINT '	- Удаление документа ИНВЕНТАРИЗАЦИЯ МАГАЗИНА'

TRUNCATE TABLE t_Est
TRUNCATE TABLE t_EstD
PRINT '	- Удаление документа ПЕРЕОЦЕНКА ПАРТИЙ МАГАЗИНА'

TRUNCATE TABLE t_Cst
TRUNCATE TABLE t_CstD
PRINT '	- Удаление документа ПРИХОД В МАГАЗИН ПО ГТД'

TRUNCATE TABLE t_Dis
TRUNCATE TABLE t_DisD
TRUNCATE TABLE t_DisDD
PRINT '	- Удаление документа РАСПРЕДЕЛЕНИЕ ТОВАРА МАГАЗИНА'

TRUNCATE TABLE t_EOExp
TRUNCATE TABLE t_EOExpD
TRUNCATE TABLE t_EOExpDD
PRINT '	- Удаление документа ЗАКАЗ ВНЕШНИЙ МАГАЗИНА (ФОРМИРОВАНИЕ)'

TRUNCATE TABLE t_EORec
TRUNCATE TABLE t_EORecD
PRINT '	- Удаление документа ЗАКАЗ ВНЕШНИЙ МАГАЗИНА (ПРИХОД)'

TRUNCATE TABLE t_IORec
TRUNCATE TABLE t_IORecD
PRINT '	- Удаление документа ЗАКАЗ ВНУТРЕННИЙ МАГАЗИНА (ФОРМИРОВАНИЕ)'

TRUNCATE TABLE t_IOExp
TRUNCATE TABLE t_IOExpD
PRINT '	- Удаление документа ЗАКАЗ ВНУТРЕННИЙ МАГАЗИНА (РАСХОД)'

TRUNCATE TABLE t_SRec
TRUNCATE TABLE t_SRecE
TRUNCATE TABLE t_SRecA
TRUNCATE TABLE t_SRecM
TRUNCATE TABLE t_SRecD
PRINT '	- Удаление документа КОМПЛЕКТАЦИЯ МАГАЗИНА'

TRUNCATE TABLE t_SExp
TRUNCATE TABLE t_SExpE
TRUNCATE TABLE t_SExpA
TRUNCATE TABLE t_SExpM
TRUNCATE TABLE t_SExpD
PRINT '	- Удаление документа РАЗУКОМПЛЕКТАЦИЯ МАГАЗИНА'

TRUNCATE TABLE t_SPRec
TRUNCATE TABLE t_SPRecE
TRUNCATE TABLE t_SPRecA
TRUNCATE TABLE t_SPRecM
TRUNCATE TABLE t_SPRecD
PRINT '	- Удаление документа КОМПЛЕКТАЦИЯ МАГАЗИНА (ПРОЕКТ)'

TRUNCATE TABLE t_SPExp
TRUNCATE TABLE t_SPExpE
TRUNCATE TABLE t_SPExpA
TRUNCATE TABLE t_SPExpM
TRUNCATE TABLE t_SPExpD
PRINT '	- Удаление документа РАЗУКОМПЛЕКТАЦИЯ МАГАЗИНА (ПРОЕКТ)'

TRUNCATE TABLE t_Cos
TRUNCATE TABLE t_CosD
PRINT '	- Удаление документа ФОРМИРОВАНИЕ СЕБЕСТОИМОСТИ МАГАЗИНА'

TRUNCATE TABLE t_SEst
TRUNCATE TABLE t_SEstD
PRINT '	- Удаление документа ПЕРЕОЦЕНКА ЦЕН ПРОДАЖИ МАГАЗИНА'

TRUNCATE TABLE t_MRec
PRINT '	- Удаление документа СЛУЖЕБНЫЙ ПРИХОД ДЕНЕГ В ЭККА'

TRUNCATE TABLE t_MExp
PRINT '	- Удаление документа СЛУЖЕБНЫЙ РАСХОД ДЕНЕГ ИЗ ЭККА'

TRUNCATE TABLE b_CExp
TRUNCATE TABLE t_RecPO
TRUNCATE TABLE t_RecPR
PRINT '	- Удаление документа КАССОВЫЙ ОРДЕР РАСХОДА'

TRUNCATE TABLE t_PinPCh
PRINT '	- Удаление документа ИЗМЕНЕНИЕ ЦЕН ПРИХОДА ТОРГОВЛИ'

TRUNCATE TABLE r_ProdMPCh
PRINT '	- Удаление документа ИЗМЕНЕНИЕ ЦЕН ПРОДАЖИ'

TRUNCATE TABLE t_xAnn
TRUNCATE TABLE t_xGen
TRUNCATE TABLE t_xOper
TRUNCATE TABLE t_xOperD
PRINT '	- Удаление документа ОТЧЕТЫ КАССОВОГО АППАРАТА'

TRUNCATE TABLE _Ch
PRINT '	- Очистка ЖУРНАЛА РЕГИСТРАЦИИ ДЕЙСТВИЙ ПОЛЬЗОВАТЕЛЯ'

-- во во вот тут дописать новые таблички иначе торговый клиент не пашет

 
truncate table z_DocList
truncate table z_DocList_B1 
TRUNCATE TABLE z_DocList_B2
TRUNCATE TABLE z_DocList_C
TRUNCATE TABLE z_DocList_S
TRUNCATE TABLE z_DocList_T
TRUNCATE TABLE z_DocListMG
insert into z_DocList (GrndID,DocType,OurID ,CompID,SrcChID,SrcDocID,SrcDocDate) 
			values (0,0,1,0,0,0,01/01/1900)

insert into z_DocList_B1 values (0)
insert into z_DocList_B2 values (0)
insert into z_DocList_C values (0)
insert into z_DocList_S values (0)
insert into z_DocList_T values (0)
insert into z_DocListMG values (0,0,0)
PRINT '	- Очистка ЖУРНАЛА ОСНОВАНИЙ'

--DROP TABLE _Temp_t_ZinP
DROP TABLE _Temp_t_PinP

/*PRINT 'Удаление карточек товара, которые находятся в стоп-списке'
UPDATE r_Prods
SET InStopList = 1
FROM r_Prods
WHERE ProdName LIKE '@%' AND InStopList = 0

UPDATE r_Prods
SET ProdName = '@@'+ Notes
FROM r_Prods
WHERE ProdName NOT LIKE '@%' AND InStopList = 1

UPDATE r_Prods
SET InStopList = 0
FROM r_Prods
INNER JOIN t_Rem ON r_Prods.ProdID=t_Rem.ProdID
WHERE r_Prods.InStopList = 1

DELETE FROM r_Prods
WHERE InStopList=1

UPDATE r_Prods
SET InStopList = 1
FROM r_Prods
WHERE ProdName LIKE '@%' AND InStopList = 0

PRINT 'Производится расчёт текущих остатков. Пожалуйста подождите...'
SELECT (t_PRemReady)
FROM z_SysApps

UPDATE z_SysApps
SET t_PRemReady = 0

SELECT SUM (Qty)
FROM t_Rem

SELECT *
FROM t__BProd

TRUNCATE TABLE t_Remx

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(0 - Qty*10)
FROM t_ExpsE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(Qty*10)
FROM t_RecsE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(Qty*10)
FROM t_CRRetsE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(0 - Qty*10)
FROM t_SalesE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(0 - Qty*10)
FROM t_CRSalesE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(Qty*10)
FROM t_zInPsE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(Qty*10)
FROM t_ExcsER
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(0 - Qty*10)
FROM t_ExcsEE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(Qty*10)
FROM t_VensER
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(0 - Qty*10)
FROM t_VensEE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(Qty*10)
FROM t_EstsER
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(0 - Qty*10)
FROM t_EstsEE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(0 - Qty*10)
FROM t_EppsE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(Qty*10)
FROM t_RetsE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(0 - Qty*10)
FROM t_SExpsEE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(Qty*10)
FROM t_SExpsER
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(0 - Qty*10)
FROM t_SRecsEE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(Qty*10)
FROM t_SRecsER
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(Qty*10)
FROM t_CstsE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecId, ProdID, PPID, SUM(0 - Qty*10)
FROM t_CRetsE
WHERE InRems<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

INSERT INTO t_Remx (OurID, StockID, SecID, ProdID, PPID, Qty)
SELECT OurID, StockID, SecID, ProdID, PPID, SUM(0 - Qty*10)
FROM t_AccsE
WHERE InRems<>0  AND ReserveProds<>0
GROUP BY OurID, StockID, SecID, ProdID, PPID

UPDATE t_Rem
SET Qty=0
WHERE Qty IS NULL

DELETE FROM t_Rem

INSERT INTO t_Rem (OurID, StockID, SecId, ProdID, PPID, Qty)
SELECT OurID, StockID, SecID, ProdID, PPID, SUM(Qty)/10
FROM t_Remx
GROUP BY OurID, StockID, SecID, ProdID, PPID
ORDER BY OurID, StockID, SecID, ProdID, PPID

SELECT (t_RZ)
FROM z_Sys

TRUNCATE TABLE t_Remx

SELECT SUM (Qty)
FROM t_Rem

UPDATE STATISTICS t_Rem

UPDATE z_SysApps
SET t_PRemReady = 1

PRINT 'Производится восстановление базы данных. Пожалуйста подождите...'
UPDATE z_SysApps SET s_PRemDReady=1, s_PRemReady=1, b_PRemDReady=1, b_PRemReady=1
exec [OTData_M6]..sp_check_constraints_rowset N'CK_s_Rem_AllowNegative', NULL
UPDATE z_Sys SET s_ZR=1
exec [OTData_M6]..sp_check_constraints_rowset N'CK_b_Rem_AllowNegative', NULL
UPDATE z_Sys SET b_ZR=1
exec [OTData_M6]..sp_check_constraints_rowset N'CK_t_Rem_AllowNegative', NULL
UPDATE z_Sys SET b_ZR=1
INSERT INTO r_Assets_B(AssID) SELECT AssID FROM r_Assets WHERE AssID NOT IN (SELECT AssID FROM r_Assets_B)
INSERT INTO r_Carrs_B1(CarrID) SELECT CarrID FROM r_Carrs WHERE CarrID NOT IN (SELECT CarrID FROM r_Carrs_B1)
INSERT INTO r_Carrs_B2(CarrID) SELECT CarrID FROM r_Carrs WHERE CarrID NOT IN (SELECT CarrID FROM r_Carrs_B2)
INSERT INTO r_Codes1_B1 (CodeID1) SELECT CodeID1 FROM r_Codes1 WHERE CodeID1 NOT IN (SELECT CodeID1 FROM r_Codes1_B1)
INSERT INTO r_Codes1_B2 (CodeID1) SELECT CodeID1 FROM r_Codes1 WHERE CodeID1 NOT IN (SELECT CodeID1 FROM r_Codes1_B2)
INSERT INTO r_Codes1_B3 (CodeID1) SELECT CodeID1 FROM r_Codes1 WHERE CodeID1 NOT IN (SELECT CodeID1 FROM r_Codes1_B3)
INSERT INTO r_Codes1_C (CodeID1) SELECT CodeID1 FROM r_Codes1 WHERE CodeID1 NOT IN (SELECT CodeID1 FROM r_Codes1_C)
INSERT INTO r_Codes1_T1 (CodeID1) SELECT CodeID1 FROM r_Codes1 WHERE CodeID1 NOT IN (SELECT CodeID1 FROM r_Codes1_T1)
INSERT INTO r_Codes1_T2 (CodeID1) SELECT CodeID1 FROM r_Codes1 WHERE CodeID1 NOT IN (SELECT CodeID1 FROM r_Codes1_T2)
INSERT INTO r_Codes1_E (CodeID1) SELECT CodeID1 FROM r_Codes1 WHERE CodeID1 NOT IN (SELECT CodeID1 FROM r_Codes1_E)
INSERT INTO r_Codes1_S1 (CodeID1) SELECT CodeID1 FROM r_Codes1 WHERE CodeID1 NOT IN (SELECT CodeID1 FROM r_Codes1_S1)
INSERT INTO r_Codes1_S2 (CodeID1) SELECT CodeID1 FROM r_Codes1 WHERE CodeID1 NOT IN (SELECT CodeID1 FROM r_Codes1_S2)
INSERT INTO r_Codes1_P (CodeID1) SELECT CodeID1 FROM r_Codes1 WHERE CodeID1 NOT IN (SELECT CodeID1 FROM r_Codes1_P)
INSERT INTO r_Codes1_N (CodeID1) SELECT CodeID1 FROM r_Codes1 WHERE CodeID1 NOT IN (SELECT CodeID1 FROM r_Codes1_N)
INSERT INTO r_Codes2_B1 (CodeID2) SELECT CodeID2 FROM r_Codes2 WHERE CodeID2 NOT IN (SELECT CodeID2 FROM r_Codes2_B1)
INSERT INTO r_Codes2_B2 (CodeID2) SELECT CodeID2 FROM r_Codes2 WHERE CodeID2 NOT IN (SELECT CodeID2 FROM r_Codes2_B2)
INSERT INTO r_Codes2_B3 (CodeID2) SELECT CodeID2 FROM r_Codes2 WHERE CodeID2 NOT IN (SELECT CodeID2 FROM r_Codes2_B3)
INSERT INTO r_Codes2_C (CodeID2) SELECT CodeID2 FROM r_Codes2 WHERE CodeID2 NOT IN (SELECT CodeID2 FROM r_Codes2_C)
INSERT INTO r_Codes2_T1 (CodeID2) SELECT CodeID2 FROM r_Codes2 WHERE CodeID2 NOT IN (SELECT CodeID2 FROM r_Codes2_T1)
INSERT INTO r_Codes2_T2 (CodeID2) SELECT CodeID2 FROM r_Codes2 WHERE CodeID2 NOT IN (SELECT CodeID2 FROM r_Codes2_T2)
INSERT INTO r_Codes2_E (CodeID2) SELECT CodeID2 FROM r_Codes2 WHERE CodeID2 NOT IN (SELECT CodeID2 FROM r_Codes2_E)
INSERT INTO r_Codes2_S1 (CodeID2) SELECT CodeID2 FROM r_Codes2 WHERE CodeID2 NOT IN (SELECT CodeID2 FROM r_Codes2_S1)
INSERT INTO r_Codes2_S2 (CodeID2) SELECT CodeID2 FROM r_Codes2 WHERE CodeID2 NOT IN (SELECT CodeID2 FROM r_Codes2_S2)
INSERT INTO r_Codes2_P (CodeID2) SELECT CodeID2 FROM r_Codes2 WHERE CodeID2 NOT IN (SELECT CodeID2 FROM r_Codes2_P)
INSERT INTO r_Codes2_N (CodeID2) SELECT CodeID2 FROM r_Codes2 WHERE CodeID2 NOT IN (SELECT CodeID2 FROM r_Codes2_N)
INSERT INTO r_Codes3_B1 (CodeID3) SELECT CodeID3 FROM r_Codes3 WHERE CodeID3 NOT IN (SELECT CodeID3 FROM r_Codes3_B1)
INSERT INTO r_Codes3_B2 (CodeID3) SELECT CodeID3 FROM r_Codes3 WHERE CodeID3 NOT IN (SELECT CodeID3 FROM r_Codes3_B2)
INSERT INTO r_Codes3_B3 (CodeID3) SELECT CodeID3 FROM r_Codes3 WHERE CodeID3 NOT IN (SELECT CodeID3 FROM r_Codes3_B3)
INSERT INTO r_Codes3_C (CodeID3) SELECT CodeID3 FROM r_Codes3 WHERE CodeID3 NOT IN (SELECT CodeID3 FROM r_Codes3_C)
INSERT INTO r_Codes3_T1 (CodeID3) SELECT CodeID3 FROM r_Codes3 WHERE CodeID3 NOT IN (SELECT CodeID3 FROM r_Codes3_T1)
INSERT INTO r_Codes3_T2 (CodeID3) SELECT CodeID3 FROM r_Codes3 WHERE CodeID3 NOT IN (SELECT CodeID3 FROM r_Codes3_T2)
INSERT INTO r_Codes3_E (CodeID3) SELECT CodeID3 FROM r_Codes3 WHERE CodeID3 NOT IN (SELECT CodeID3 FROM r_Codes3_E)
INSERT INTO r_Codes3_S1 (CodeID3) SELECT CodeID3 FROM r_Codes3 WHERE CodeID3 NOT IN (SELECT CodeID3 FROM r_Codes3_S1)
INSERT INTO r_Codes3_S2 (CodeID3) SELECT CodeID3 FROM r_Codes3 WHERE CodeID3 NOT IN (SELECT CodeID3 FROM r_Codes3_S2)
INSERT INTO r_Codes3_P (CodeID3) SELECT CodeID3 FROM r_Codes3 WHERE CodeID3 NOT IN (SELECT CodeID3 FROM r_Codes3_P)
INSERT INTO r_Codes3_N (CodeID3) SELECT CodeID3 FROM r_Codes3 WHERE CodeID3 NOT IN (SELECT CodeID3 FROM r_Codes3_N)
INSERT INTO r_Codes4_B1 (CodeID4) SELECT CodeID4 FROM r_Codes4 WHERE CodeID4 NOT IN (SELECT CodeID4 FROM r_Codes4_B1)
INSERT INTO r_Codes4_B2 (CodeID4) SELECT CodeID4 FROM r_Codes4 WHERE CodeID4 NOT IN (SELECT CodeID4 FROM r_Codes4_B2)
INSERT INTO r_Codes4_B3 (CodeID4) SELECT CodeID4 FROM r_Codes4 WHERE CodeID4 NOT IN (SELECT CodeID4 FROM r_Codes4_B3)
INSERT INTO r_Codes4_C (CodeID4) SELECT CodeID4 FROM r_Codes4 WHERE CodeID4 NOT IN (SELECT CodeID4 FROM r_Codes4_C)
INSERT INTO r_Codes4_T1 (CodeID4) SELECT CodeID4 FROM r_Codes4 WHERE CodeID4 NOT IN (SELECT CodeID4 FROM r_Codes4_T1)
INSERT INTO r_Codes4_T2 (CodeID4) SELECT CodeID4 FROM r_Codes4 WHERE CodeID4 NOT IN (SELECT CodeID4 FROM r_Codes4_T2)
INSERT INTO r_Codes4_E (CodeID4) SELECT CodeID4 FROM r_Codes4 WHERE CodeID4 NOT IN (SELECT CodeID4 FROM r_Codes4_E)
INSERT INTO r_Codes4_S1 (CodeID4) SELECT CodeID4 FROM r_Codes4 WHERE CodeID4 NOT IN (SELECT CodeID4 FROM r_Codes4_S1)
INSERT INTO r_Codes4_S2 (CodeID4) SELECT CodeID4 FROM r_Codes4 WHERE CodeID4 NOT IN (SELECT CodeID4 FROM r_Codes4_S2)
INSERT INTO r_Codes4_P (CodeID4) SELECT CodeID4 FROM r_Codes4 WHERE CodeID4 NOT IN (SELECT CodeID4 FROM r_Codes4_P)
INSERT INTO r_Codes4_N (CodeID4) SELECT CodeID4 FROM r_Codes4 WHERE CodeID4 NOT IN (SELECT CodeID4 FROM r_Codes4_N)
INSERT INTO r_Codes5_B1 (CodeID5) SELECT CodeID5 FROM r_Codes5 WHERE CodeID5 NOT IN (SELECT CodeID5 FROM r_Codes5_B1)
INSERT INTO r_Codes5_B2 (CodeID5) SELECT CodeID5 FROM r_Codes5 WHERE CodeID5 NOT IN (SELECT CodeID5 FROM r_Codes5_B2)
INSERT INTO r_Codes5_B3 (CodeID5) SELECT CodeID5 FROM r_Codes5 WHERE CodeID5 NOT IN (SELECT CodeID5 FROM r_Codes5_B3)
INSERT INTO r_Codes5_C (CodeID5) SELECT CodeID5 FROM r_Codes5 WHERE CodeID5 NOT IN (SELECT CodeID5 FROM r_Codes5_C)
INSERT INTO r_Codes5_T1 (CodeID5) SELECT CodeID5 FROM r_Codes5 WHERE CodeID5 NOT IN (SELECT CodeID5 FROM r_Codes5_T1)
INSERT INTO r_Codes5_T2 (CodeID5) SELECT CodeID5 FROM r_Codes5 WHERE CodeID5 NOT IN (SELECT CodeID5 FROM r_Codes5_T2)
INSERT INTO r_Codes5_E (CodeID5) SELECT CodeID5 FROM r_Codes5 WHERE CodeID5 NOT IN (SELECT CodeID5 FROM r_Codes5_E)
INSERT INTO r_Codes5_S1 (CodeID5) SELECT CodeID5 FROM r_Codes5 WHERE CodeID5 NOT IN (SELECT CodeID5 FROM r_Codes5_S1)
INSERT INTO r_Codes5_S2 (CodeID5) SELECT CodeID5 FROM r_Codes5 WHERE CodeID5 NOT IN (SELECT CodeID5 FROM r_Codes5_S2)
INSERT INTO r_Codes5_P (CodeID5) SELECT CodeID5 FROM r_Codes5 WHERE CodeID5 NOT IN (SELECT CodeID5 FROM r_Codes5_P)
INSERT INTO r_Codes5_N (CodeID5) SELECT CodeID5 FROM r_Codes5 WHERE CodeID5 NOT IN (SELECT CodeID5 FROM r_Codes5_N)
INSERT INTO r_Comps_B1 (CompID) SELECT CompID FROM r_Comps WHERE CompID NOT IN (SELECT CompID FROM r_Comps_B1)
INSERT INTO r_Comps_B2 (CompID) SELECT CompID FROM r_Comps WHERE CompID NOT IN (SELECT CompID FROM r_Comps_B2)
INSERT INTO r_Comps_S (CompID) SELECT CompID FROM r_Comps WHERE CompID NOT IN (SELECT CompID FROM r_Comps_S)
INSERT INTO r_Comps_C (CompID) SELECT CompID FROM r_Comps WHERE CompID NOT IN (SELECT CompID FROM r_Comps_C)
INSERT INTO r_Comps_T (CompID) SELECT CompID FROM r_Comps WHERE CompID NOT IN (SELECT CompID FROM r_Comps_T)
INSERT INTO r_Comps_P (CompID) SELECT CompID FROM r_Comps WHERE CompID NOT IN (SELECT CompID FROM r_Comps_P)
INSERT INTO r_Comps_E1 (CompID) SELECT CompID FROM r_Comps WHERE CompID NOT IN (SELECT CompID FROM r_Comps_E1)
INSERT INTO r_Comps_E2 (CompID) SELECT CompID FROM r_Comps WHERE CompID NOT IN (SELECT CompID FROM r_Comps_E2)
INSERT INTO r_Comps_R (CompID) SELECT CompID FROM r_Comps WHERE CompID NOT IN (SELECT CompID FROM r_Comps_R)
INSERT INTO r_Currs_B1 (CurrID) SELECT CurrID FROM r_Currs WHERE CurrID NOT IN (SELECT CurrID FROM r_Currs_B1)
INSERT INTO r_Currs_B2 (CurrID) SELECT CurrID FROM r_Currs WHERE CurrID NOT IN (SELECT CurrID FROM r_Currs_B2)
INSERT INTO r_Currs_C (CurrID) SELECT CurrID FROM r_Currs WHERE CurrID NOT IN (SELECT CurrID FROM r_Currs_C)
INSERT INTO r_Currs_R (CurrID) SELECT CurrID FROM r_Currs WHERE CurrID NOT IN (SELECT CurrID FROM r_Currs_R)
INSERT INTO r_Currs_N (CurrID) SELECT CurrID FROM r_Currs WHERE CurrID NOT IN (SELECT CurrID FROM r_Currs_N)
INSERT INTO r_Emps_B1 (EmpID) SELECT EmpID FROM r_Emps WHERE EmpID NOT IN (SELECT EmpID FROM r_Emps_B1)
INSERT INTO r_Emps_B2 (EmpID) SELECT EmpID FROM r_Emps WHERE EmpID NOT IN (SELECT EmpID FROM r_Emps_B2)
INSERT INTO r_Emps_C (EmpID) SELECT EmpID FROM r_Emps WHERE EmpID NOT IN (SELECT EmpID FROM r_Emps_C)
INSERT INTO r_Emps_P1 (EmpID) SELECT EmpID FROM r_Emps WHERE EmpID NOT IN (SELECT EmpID FROM r_Emps_P1)
INSERT INTO r_Emps_P2 (EmpID) SELECT EmpID FROM r_Emps WHERE EmpID NOT IN (SELECT EmpID FROM r_Emps_P2)
INSERT INTO r_Emps_N1 (EmpID) SELECT EmpID FROM r_Emps WHERE EmpID NOT IN (SELECT EmpID FROM r_Emps_N1)
INSERT INTO r_Emps_N2 (EmpID) SELECT EmpID FROM r_Emps WHERE EmpID NOT IN (SELECT EmpID FROM r_Emps_N2)
INSERT INTO r_Emps_R (EmpID) SELECT EmpID FROM r_Emps WHERE EmpID NOT IN (SELECT EmpID FROM r_Emps_R)
INSERT INTO r_Emps_S (EmpID) SELECT EmpID FROM r_Emps WHERE EmpID NOT IN (SELECT EmpID FROM r_Emps_S)
INSERT INTO r_Emps_T (EmpID) SELECT EmpID FROM r_Emps WHERE EmpID NOT IN (SELECT EmpID FROM r_Emps_T)
INSERT INTO r_GAccs_B1 (GAccID) SELECT GAccID FROM r_GAccs WHERE GAccID NOT IN (SELECT GAccID FROM r_GAccs_B1)
INSERT INTO r_GOpers_B1 (GOperID) SELECT GOperID FROM r_GOpers WHERE GOperID NOT IN (SELECT GOperID FROM r_GOpers_B1)
INSERT INTO r_GOpers_B2 (GOperID) SELECT GOperID FROM r_GOpers WHERE GOperID NOT IN (SELECT GOperID FROM r_GOpers_B2)
INSERT INTO r_GOpers_P (GOperID) SELECT GOperID FROM r_GOpers WHERE GOperID NOT IN (SELECT GOperID FROM r_GOpers_P)
INSERT INTO r_GOpers_B3 (GOperID) SELECT GOperID FROM r_GOpers WHERE GOperID NOT IN (SELECT GOperID FROM r_GOpers_B3)
INSERT INTO r_GVols_B (GVolID) SELECT GVolID FROM r_GVols WHERE GVolID NOT IN (SELECT GVolID FROM r_GVols_B)
INSERT INTO r_Ours_B1 (OurID) SELECT OurID FROM r_Ours WHERE OurID NOT IN (SELECT OurID FROM r_Ours_B1)
INSERT INTO r_Ours_B2 (OurID) SELECT OurID FROM r_Ours WHERE OurID NOT IN (SELECT OurID FROM r_Ours_B2)
INSERT INTO r_Ours_S (OurID) SELECT OurID FROM r_Ours WHERE OurID NOT IN (SELECT OurID FROM r_Ours_S)
INSERT INTO r_Ours_C (OurID) SELECT OurID FROM r_Ours WHERE OurID NOT IN (SELECT OurID FROM r_Ours_C)
INSERT INTO r_Ours_T1 (OurID) SELECT OurID FROM r_Ours WHERE OurID NOT IN (SELECT OurID FROM r_Ours_T1)
INSERT INTO r_Ours_T2 (OurID) SELECT OurID FROM r_Ours WHERE OurID NOT IN (SELECT OurID FROM r_Ours_T2)
INSERT INTO r_Ours_E (OurID) SELECT OurID FROM r_Ours WHERE OurID NOT IN (SELECT OurID FROM r_Ours_E)
INSERT INTO r_Ours_P (OurID) SELECT OurID FROM r_Ours WHERE OurID NOT IN (SELECT OurID FROM r_Ours_P)
INSERT INTO r_Ours_N (OurID) SELECT OurID FROM r_Ours WHERE OurID NOT IN (SELECT OurID FROM r_Ours_N)
INSERT INTO r_Prods_R (ProdID) SELECT ProdID FROM r_Prods WHERE ProdID NOT IN (SELECT ProdID FROM r_Prods_R)
INSERT INTO r_Secs_T (SecID) SELECT SecID FROM r_Secs WHERE SecID NOT IN (SELECT SecID FROM r_Secs_T)
INSERT INTO r_Stocks_B1 (StockID) SELECT StockID FROM r_Stocks WHERE StockID NOT IN (SELECT StockID FROM r_Stocks_B1)
INSERT INTO r_Stocks_B2 (StockID) SELECT StockID FROM r_Stocks WHERE StockID NOT IN (SELECT StockID FROM r_Stocks_B2)
INSERT INTO r_Stocks_T1 (StockID) SELECT StockID FROM r_Stocks WHERE StockID NOT IN (SELECT StockID FROM r_Stocks_T1)
INSERT INTO r_Stocks_T2 (StockID) SELECT StockID FROM r_Stocks WHERE StockID NOT IN (SELECT StockID FROM r_Stocks_T2)
INSERT INTO r_Stocks_E1 (StockID) SELECT StockID FROM r_Stocks WHERE StockID NOT IN (SELECT StockID FROM r_Stocks_E1)
INSERT INTO r_Stocks_E2 (StockID) SELECT StockID FROM r_Stocks WHERE StockID NOT IN (SELECT StockID FROM r_Stocks_E2)
INSERT INTO r_Stocks_C (StockID) SELECT StockID FROM r_Stocks WHERE StockID NOT IN (SELECT StockID FROM r_Stocks_C)
INSERT INTO r_Stocks_S1 (StockID) SELECT StockID FROM r_Stocks WHERE StockID NOT IN (SELECT StockID FROM r_Stocks_S1)
INSERT INTO r_Stocks_S2 (StockID) SELECT StockID FROM r_Stocks WHERE StockID NOT IN (SELECT StockID FROM r_Stocks_S2)
INSERT INTO s_PInP_S(ProdID, PPID) SELECT ProdID, PPID FROM s_PInP WHERE (SELECT Count(*) FROM s_PInP_S WHERE s_PInP_S.ProdID=s_PInP.ProdID AND s_PInP_S.PPID=s_PInP.PPID)=0
INSERT INTO t_PInP_T(ProdID, PPID) SELECT ProdID, PPID FROM t_PInP WHERE (SELECT Count(*) FROM t_PInP_T WHERE t_PInP_T.ProdID=t_PInP.ProdID AND t_PInP_T.PPID=t_PInP.PPID)=0

PRINT 'Производится обновление статистики. Пожалуйста подождите...'
UPDATE STATISTICS dbo._Apps
UPDATE STATISTICS dbo._BComp
UPDATE STATISTICS dbo._Ch
UPDATE STATISTICS dbo._ChD
UPDATE STATISTICS dbo._Docs
UPDATE STATISTICS dbo._Docs_R
UPDATE STATISTICS dbo._Fields
UPDATE STATISTICS dbo._Groups
UPDATE STATISTICS dbo._MapDT
UPDATE STATISTICS dbo._MapGU
UPDATE STATISTICS dbo._MapTF
UPDATE STATISTICS dbo._PermsD
UPDATE STATISTICS dbo._PermsG
UPDATE STATISTICS dbo._PermsU
UPDATE STATISTICS dbo._PForm
UPDATE STATISTICS dbo._PFormD
UPDATE STATISTICS dbo._PFormE
UPDATE STATISTICS dbo._PFormEC
UPDATE STATISTICS dbo._Rels
UPDATE STATISTICS dbo._RelsD
UPDATE STATISTICS dbo._Tables
UPDATE STATISTICS dbo._Tables_R

UPDATE STATISTICS dbo.b__BAC
UPDATE STATISTICS dbo.b__BCA
UPDATE STATISTICS dbo.b__BCC
UPDATE STATISTICS dbo.b__BEmp
UPDATE STATISTICS dbo.b__BProd
UPDATE STATISTICS dbo.b__WAssets
UPDATE STATISTICS dbo.b__WLCopy
UPDATE STATISTICS dbo.b__WPCopy
UPDATE STATISTICS dbo.b__WRate
UPDATE STATISTICS dbo.b__WSCopy
UPDATE STATISTICS dbo.b__WSCopyD
UPDATE STATISTICS dbo.b__WSCopyDU
UPDATE STATISTICS dbo.b__WSCopyG
UPDATE STATISTICS dbo.b__WSCopyT
UPDATE STATISTICS dbo.b_Acc
UPDATE STATISTICS dbo.b_AccD
UPDATE STATISTICS dbo.b_AExp
UPDATE STATISTICS dbo.b_AExpPA
UPDATE STATISTICS dbo.b_AExpPB
UPDATE STATISTICS dbo.b_AExpPC
UPDATE STATISTICS dbo.b_AExpPO
UPDATE STATISTICS dbo.b_ARec
UPDATE STATISTICS dbo.b_ARecPA
UPDATE STATISTICS dbo.b_ARecPB
UPDATE STATISTICS dbo.b_ARecPC
UPDATE STATISTICS dbo.b_ARecPO
UPDATE STATISTICS dbo.b_ARepA
UPDATE STATISTICS dbo.b_ARepADP
UPDATE STATISTICS dbo.b_ARepADS
UPDATE STATISTICS dbo.b_ARepADV
UPDATE STATISTICS dbo.b_BAExp
UPDATE STATISTICS dbo.b_BAExpD
UPDATE STATISTICS dbo.b_BAPay
UPDATE STATISTICS dbo.b_BARec
UPDATE STATISTICS dbo.b_BARecD
UPDATE STATISTICS dbo.b_BCExp
UPDATE STATISTICS dbo.b_BCExpD
UPDATE STATISTICS dbo.b_BCPay
UPDATE STATISTICS dbo.b_BCRec
UPDATE STATISTICS dbo.b_BCRecD
UPDATE STATISTICS dbo.b_CExp
UPDATE STATISTICS dbo.b_CInv
UPDATE STATISTICS dbo.b_CInvD
UPDATE STATISTICS dbo.b_CRec
UPDATE STATISTICS dbo.b_CRepA
UPDATE STATISTICS dbo.b_CRepADP
UPDATE STATISTICS dbo.b_CRepADS
UPDATE STATISTICS dbo.b_CRepADV
UPDATE STATISTICS dbo.b_CRet
UPDATE STATISTICS dbo.b_CRetD
UPDATE STATISTICS dbo.b_Cst
UPDATE STATISTICS dbo.b_CstD
UPDATE STATISTICS dbo.b_DStack
UPDATE STATISTICS dbo.b_Exp
UPDATE STATISTICS dbo.b_ExpD
UPDATE STATISTICS dbo.b_GTran
UPDATE STATISTICS dbo.b_GTranD
UPDATE STATISTICS dbo.b_GView
UPDATE STATISTICS dbo.b_GViewD
UPDATE STATISTICS dbo.b_GViewU
UPDATE STATISTICS dbo.b_Inv
UPDATE STATISTICS dbo.b_InvD
UPDATE STATISTICS dbo.b_LExp
UPDATE STATISTICS dbo.b_LExpD
UPDATE STATISTICS dbo.b_LRec
UPDATE STATISTICS dbo.b_LRecD
UPDATE STATISTICS dbo.b_MapDO
UPDATE STATISTICS dbo.b_PAcc
UPDATE STATISTICS dbo.b_PAccD
UPDATE STATISTICS dbo.b_PEst
UPDATE STATISTICS dbo.b_PEstD
UPDATE STATISTICS dbo.b_PExc
UPDATE STATISTICS dbo.b_PExcD
UPDATE STATISTICS dbo.b_PInP
UPDATE STATISTICS dbo.b_PVen
UPDATE STATISTICS dbo.b_PVenA
UPDATE STATISTICS dbo.b_PVenD
UPDATE STATISTICS dbo.b_RCor
UPDATE STATISTICS dbo.b_RCorD
UPDATE STATISTICS dbo.b_Rec
UPDATE STATISTICS dbo.b_RecD
UPDATE STATISTICS dbo.b_RECor
UPDATE STATISTICS dbo.b_RECorD
UPDATE STATISTICS dbo.b_Rem
UPDATE STATISTICS dbo.b_RemD
UPDATE STATISTICS dbo.b_Remx
UPDATE STATISTICS dbo.b_RepA
UPDATE STATISTICS dbo.b_RepADP
UPDATE STATISTICS dbo.b_RepADS
UPDATE STATISTICS dbo.b_RepADV
UPDATE STATISTICS dbo.b_Ret
UPDATE STATISTICS dbo.b_RetD
UPDATE STATISTICS dbo.b_SDep
UPDATE STATISTICS dbo.b_SDepD
UPDATE STATISTICS dbo.b_SExc
UPDATE STATISTICS dbo.b_SExcD
UPDATE STATISTICS dbo.b_SExp
UPDATE STATISTICS dbo.b_SExpD
UPDATE STATISTICS dbo.b_SInv
UPDATE STATISTICS dbo.b_SInvD
UPDATE STATISTICS dbo.b_SPut
UPDATE STATISTICS dbo.b_SPutD
UPDATE STATISTICS dbo.b_SRec
UPDATE STATISTICS dbo.b_SRecD
UPDATE STATISTICS dbo.b_SRep
UPDATE STATISTICS dbo.b_SRepDP
UPDATE STATISTICS dbo.b_SRepDV
UPDATE STATISTICS dbo.b_SVen
UPDATE STATISTICS dbo.b_SVenD
UPDATE STATISTICS dbo.b_SWer
UPDATE STATISTICS dbo.b_SWerD
UPDATE STATISTICS dbo.b_TExp
UPDATE STATISTICS dbo.b_TranC
UPDATE STATISTICS dbo.b_TranE
UPDATE STATISTICS dbo.b_TranH
UPDATE STATISTICS dbo.b_TranP
UPDATE STATISTICS dbo.b_TranS
UPDATE STATISTICS dbo.b_TranV
UPDATE STATISTICS dbo.b_TRec
UPDATE STATISTICS dbo.b_WBill
UPDATE STATISTICS dbo.b_WBillA
UPDATE STATISTICS dbo.b_WBillD
UPDATE STATISTICS dbo.b_zInBA
UPDATE STATISTICS dbo.b_zInBC
UPDATE STATISTICS dbo.b_zInC
UPDATE STATISTICS dbo.b_zInCA
UPDATE STATISTICS dbo.b_zInE
UPDATE STATISTICS dbo.b_zInH
UPDATE STATISTICS dbo.b_zInP
UPDATE STATISTICS dbo.b_zInS
UPDATE STATISTICS dbo.b_zInV
UPDATE STATISTICS dbo.c__BAC
UPDATE STATISTICS dbo.c__BDay
UPDATE STATISTICS dbo.c__BEmp
UPDATE STATISTICS dbo.c_CCor
UPDATE STATISTICS dbo.c_CCorD
UPDATE STATISTICS dbo.c_CExp
UPDATE STATISTICS dbo.c_CExpA
UPDATE STATISTICS dbo.c_CExpD
UPDATE STATISTICS dbo.c_CInt
UPDATE STATISTICS dbo.c_CIntD
UPDATE STATISTICS dbo.c_Cor
UPDATE STATISTICS dbo.c_CRec
UPDATE STATISTICS dbo.c_CRecA
UPDATE STATISTICS dbo.c_CRecD
UPDATE STATISTICS dbo.c_ECor
UPDATE STATISTICS dbo.c_ECorD
UPDATE STATISTICS dbo.c_EExc
UPDATE STATISTICS dbo.c_EExcD
UPDATE STATISTICS dbo.c_EExp
UPDATE STATISTICS dbo.c_EExpA
UPDATE STATISTICS dbo.c_EExpD
UPDATE STATISTICS dbo.c_EInt
UPDATE STATISTICS dbo.c_EIntD
UPDATE STATISTICS dbo.c_ERec
UPDATE STATISTICS dbo.c_ERecA
UPDATE STATISTICS dbo.c_ERecD
UPDATE STATISTICS dbo.c_ERep
UPDATE STATISTICS dbo.c_ERepA
UPDATE STATISTICS dbo.c_ERepD
UPDATE STATISTICS dbo.c_PExp
UPDATE STATISTICS dbo.c_PExpA
UPDATE STATISTICS dbo.c_PExpD
UPDATE STATISTICS dbo.c_PRec
UPDATE STATISTICS dbo.c_PRecA
UPDATE STATISTICS dbo.c_PRecD
UPDATE STATISTICS dbo.c_RCor
UPDATE STATISTICS dbo.c_RCorD
UPDATE STATISTICS dbo.c_RECor
UPDATE STATISTICS dbo.c_RECorD
UPDATE STATISTICS dbo.c_Sal
UPDATE STATISTICS dbo.c_SalD
UPDATE STATISTICS dbo.c_zInAC
UPDATE STATISTICS dbo.c_zInC
UPDATE STATISTICS dbo.c_zInE
UPDATE STATISTICS dbo.e__BProd
UPDATE STATISTICS dbo.e_CExc
UPDATE STATISTICS dbo.e_CExcD
UPDATE STATISTICS dbo.e_Ch
UPDATE STATISTICS dbo.e_Chx
UPDATE STATISTICS dbo.e_Clr
UPDATE STATISTICS dbo.e_ClrA
UPDATE STATISTICS dbo.e_ClrD
UPDATE STATISTICS dbo.e_Dry
UPDATE STATISTICS dbo.e_DryD
UPDATE STATISTICS dbo.e_Exp
UPDATE STATISTICS dbo.e_PClass
UPDATE STATISTICS dbo.e_PInP
UPDATE STATISTICS dbo.e_Pur
UPDATE STATISTICS dbo.e_PurA
UPDATE STATISTICS dbo.e_PurD
UPDATE STATISTICS dbo.e_PurR
UPDATE STATISTICS dbo.e_Qqf
UPDATE STATISTICS dbo.e_QqfD
UPDATE STATISTICS dbo.e_Rec
UPDATE STATISTICS dbo.e_RecD
UPDATE STATISTICS dbo.e_Rem
UPDATE STATISTICS dbo.e_RemD
UPDATE STATISTICS dbo.e_Remx
UPDATE STATISTICS dbo.e_Srv
UPDATE STATISTICS dbo.e_SrvD
UPDATE STATISTICS dbo.e_SrvE
UPDATE STATISTICS dbo.e_zInP
UPDATE STATISTICS dbo.n_CForm
UPDATE STATISTICS dbo.n_CFormA
UPDATE STATISTICS dbo.n_CFormC
UPDATE STATISTICS dbo.n_CFormE
UPDATE STATISTICS dbo.n_CFormKin
UPDATE STATISTICS dbo.n_CFormL
UPDATE STATISTICS dbo.n_CFormM
UPDATE STATISTICS dbo.n_CFormT
UPDATE STATISTICS dbo.n_CVac
UPDATE STATISTICS dbo.n_CVacC
UPDATE STATISTICS dbo.n_CVacE
UPDATE STATISTICS dbo.n_CVacL
UPDATE STATISTICS dbo.n_CVacM
UPDATE STATISTICS dbo.n_CVacR
UPDATE STATISTICS dbo.n_EDis
UPDATE STATISTICS dbo.n_EExc
UPDATE STATISTICS dbo.n_EForm
UPDATE STATISTICS dbo.n_EFormA
UPDATE STATISTICS dbo.n_EFormC
UPDATE STATISTICS dbo.n_EFormE
UPDATE STATISTICS dbo.n_EFormH
UPDATE STATISTICS dbo.n_EFormKin
UPDATE STATISTICS dbo.n_EFormL
UPDATE STATISTICS dbo.n_EFormM
UPDATE STATISTICS dbo.n_EFormP
UPDATE STATISTICS dbo.n_EFormT
UPDATE STATISTICS dbo.n_EGiv
UPDATE STATISTICS dbo.n_EInc
UPDATE STATISTICS dbo.n_EIncD
UPDATE STATISTICS dbo.n_ELeav
UPDATE STATISTICS dbo.n_ELeavD
UPDATE STATISTICS dbo.n_EPen
UPDATE STATISTICS dbo.n_EPenD
UPDATE STATISTICS dbo.n_ETrp
UPDATE STATISTICS dbo.n_ETrper
UPDATE STATISTICS dbo.n_LMem
UPDATE STATISTICS dbo.n_LMemD
UPDATE STATISTICS dbo.n_LStr
UPDATE STATISTICS dbo.n_LStrD
UPDATE STATISTICS dbo.p__BEmp
UPDATE STATISTICS dbo.p_CWTime
UPDATE STATISTICS dbo.p_CWTimeD
UPDATE STATISTICS dbo.p_CWTimeDD
UPDATE STATISTICS dbo.p_DTran
UPDATE STATISTICS dbo.p_EDis
UPDATE STATISTICS dbo.p_EExc
UPDATE STATISTICS dbo.p_EGiv
UPDATE STATISTICS dbo.p_ELeav
UPDATE STATISTICS dbo.p_ELeavD
UPDATE STATISTICS dbo.p_ELeavDD
UPDATE STATISTICS dbo.p_ESic
UPDATE STATISTICS dbo.p_ESicA
UPDATE STATISTICS dbo.p_ESicD
UPDATE STATISTICS dbo.p_ETrp
UPDATE STATISTICS dbo.p_EWri
UPDATE STATISTICS dbo.p_EWriP
UPDATE STATISTICS dbo.p_EWrk
UPDATE STATISTICS dbo.p_EWrkD
UPDATE STATISTICS dbo.p_LExc
UPDATE STATISTICS dbo.p_LExcD
UPDATE STATISTICS dbo.p_LExp
UPDATE STATISTICS dbo.p_LExpD
UPDATE STATISTICS dbo.p_LMem
UPDATE STATISTICS dbo.p_LMemD
UPDATE STATISTICS dbo.p_LRec
UPDATE STATISTICS dbo.p_LRecD
UPDATE STATISTICS dbo.p_LRecDD
UPDATE STATISTICS dbo.p_LStr
UPDATE STATISTICS dbo.p_LStrD
UPDATE STATISTICS dbo.p_OPWrk
UPDATE STATISTICS dbo.p_OPWrkD
UPDATE STATISTICS dbo.p_OWrk
UPDATE STATISTICS dbo.p_OWrkD
UPDATE STATISTICS dbo.p_TSer
UPDATE STATISTICS dbo.p_TSerD
UPDATE STATISTICS dbo.p_WExc
UPDATE STATISTICS dbo.r_AssetC
UPDATE STATISTICS dbo.r_AssetG
UPDATE STATISTICS dbo.r_Assets
UPDATE STATISTICS dbo.r_Assets_B
UPDATE STATISTICS dbo.r_Banks
UPDATE STATISTICS dbo.r_BDocs
UPDATE STATISTICS dbo.r_Carrs
UPDATE STATISTICS dbo.r_Carrs_B1
UPDATE STATISTICS dbo.r_Carrs_B2
UPDATE STATISTICS dbo.r_CarrsC
UPDATE STATISTICS dbo.r_CForm
UPDATE STATISTICS dbo.r_CFormMQ
UPDATE STATISTICS dbo.r_Codes1
UPDATE STATISTICS dbo.r_Codes1_B1
UPDATE STATISTICS dbo.r_Codes1_B2
UPDATE STATISTICS dbo.r_Codes1_B3
UPDATE STATISTICS dbo.r_Codes1_C
UPDATE STATISTICS dbo.r_Codes1_E
UPDATE STATISTICS dbo.r_Codes1_N
UPDATE STATISTICS dbo.r_Codes1_P
UPDATE STATISTICS dbo.r_Codes1_S1
UPDATE STATISTICS dbo.r_Codes1_S2
UPDATE STATISTICS dbo.r_Codes1_T1
UPDATE STATISTICS dbo.r_Codes1_T2
UPDATE STATISTICS dbo.r_Codes2
UPDATE STATISTICS dbo.r_Codes2_B1
UPDATE STATISTICS dbo.r_Codes2_B2
UPDATE STATISTICS dbo.r_Codes2_B3
UPDATE STATISTICS dbo.r_Codes2_C
UPDATE STATISTICS dbo.r_Codes2_E
UPDATE STATISTICS dbo.r_Codes2_N
UPDATE STATISTICS dbo.r_Codes2_P
UPDATE STATISTICS dbo.r_Codes2_S1
UPDATE STATISTICS dbo.r_Codes2_S2
UPDATE STATISTICS dbo.r_Codes2_T1
UPDATE STATISTICS dbo.r_Codes2_T2
UPDATE STATISTICS dbo.r_Codes3
UPDATE STATISTICS dbo.r_Codes3_B1
UPDATE STATISTICS dbo.r_Codes3_B2
UPDATE STATISTICS dbo.r_Codes3_B3
UPDATE STATISTICS dbo.r_Codes3_C
UPDATE STATISTICS dbo.r_Codes3_E
UPDATE STATISTICS dbo.r_Codes3_N
UPDATE STATISTICS dbo.r_Codes3_P
UPDATE STATISTICS dbo.r_Codes3_S1
UPDATE STATISTICS dbo.r_Codes3_S2
UPDATE STATISTICS dbo.r_Codes3_T1
UPDATE STATISTICS dbo.r_Codes3_T2
UPDATE STATISTICS dbo.r_Codes4
UPDATE STATISTICS dbo.r_Codes4_B1
UPDATE STATISTICS dbo.r_Codes4_B2
UPDATE STATISTICS dbo.r_Codes4_B3
UPDATE STATISTICS dbo.r_Codes4_C
UPDATE STATISTICS dbo.r_Codes4_E
UPDATE STATISTICS dbo.r_Codes4_N
UPDATE STATISTICS dbo.r_Codes4_P
UPDATE STATISTICS dbo.r_Codes4_S1
UPDATE STATISTICS dbo.r_Codes4_S2
UPDATE STATISTICS dbo.r_Codes4_T1
UPDATE STATISTICS dbo.r_Codes4_T2
UPDATE STATISTICS dbo.r_Codes5
UPDATE STATISTICS dbo.r_Codes5_B1
UPDATE STATISTICS dbo.r_Codes5_B2
UPDATE STATISTICS dbo.r_Codes5_B3
UPDATE STATISTICS dbo.r_Codes5_C
UPDATE STATISTICS dbo.r_Codes5_E
UPDATE STATISTICS dbo.r_Codes5_N
UPDATE STATISTICS dbo.r_Codes5_P
UPDATE STATISTICS dbo.r_Codes5_S1
UPDATE STATISTICS dbo.r_Codes5_S2
UPDATE STATISTICS dbo.r_Codes5_T1
UPDATE STATISTICS dbo.r_Codes5_T2
UPDATE STATISTICS dbo.r_CompG
UPDATE STATISTICS dbo.r_CompMDC
UPDATE STATISTICS dbo.r_CompMG
UPDATE STATISTICS dbo.r_Comps
UPDATE STATISTICS dbo.r_Comps_B1
UPDATE STATISTICS dbo.r_Comps_B2
UPDATE STATISTICS dbo.r_Comps_C
UPDATE STATISTICS dbo.r_Comps_E1
UPDATE STATISTICS dbo.r_Comps_E2
UPDATE STATISTICS dbo.r_Comps_P
UPDATE STATISTICS dbo.r_Comps_R
UPDATE STATISTICS dbo.r_Comps_S
UPDATE STATISTICS dbo.r_Comps_T
UPDATE STATISTICS dbo.r_CompsAC
UPDATE STATISTICS dbo.r_CompsAdd
UPDATE STATISTICS dbo.r_CompsCC
UPDATE STATISTICS dbo.r_CRMM
UPDATE STATISTICS dbo.r_CRMO
UPDATE STATISTICS dbo.r_CRMP
UPDATE STATISTICS dbo.r_CRs
UPDATE STATISTICS dbo.r_CRSrvs
UPDATE STATISTICS dbo.r_CRTaxs
UPDATE STATISTICS dbo.r_CurrH
UPDATE STATISTICS dbo.r_Currs
UPDATE STATISTICS dbo.r_Currs_B1
UPDATE STATISTICS dbo.r_Currs_B2
UPDATE STATISTICS dbo.r_Currs_C
UPDATE STATISTICS dbo.r_Currs_N
UPDATE STATISTICS dbo.r_Currs_R
UPDATE STATISTICS dbo.r_Deps
UPDATE STATISTICS dbo.r_Dis
UPDATE STATISTICS dbo.r_DisMC
UPDATE STATISTICS dbo.r_Edus
UPDATE STATISTICS dbo.r_EmpAcc
UPDATE STATISTICS dbo.r_EmpAct
UPDATE STATISTICS dbo.r_EmpAdd
UPDATE STATISTICS dbo.r_EmpInc
UPDATE STATISTICS dbo.r_EmpKin
UPDATE STATISTICS dbo.r_EmpMNst
UPDATE STATISTICS dbo.r_EmpMO
UPDATE STATISTICS dbo.r_EmpMP
UPDATE STATISTICS dbo.r_EmpMPst
UPDATE STATISTICS dbo.r_Emps
UPDATE STATISTICS dbo.r_Emps_B1
UPDATE STATISTICS dbo.r_Emps_B2
UPDATE STATISTICS dbo.r_Emps_C
UPDATE STATISTICS dbo.r_Emps_N1
UPDATE STATISTICS dbo.r_Emps_N2
UPDATE STATISTICS dbo.r_Emps_P1
UPDATE STATISTICS dbo.r_Emps_P2
UPDATE STATISTICS dbo.r_Emps_R
UPDATE STATISTICS dbo.r_Emps_S
UPDATE STATISTICS dbo.r_Emps_T
UPDATE STATISTICS dbo.r_EServs
UPDATE STATISTICS dbo.r_GAccFA
UPDATE STATISTICS dbo.r_GAccs
UPDATE STATISTICS dbo.r_GAccs_B1
UPDATE STATISTICS dbo.r_GAccs1
UPDATE STATISTICS dbo.r_GAccs2
UPDATE STATISTICS dbo.r_GOperC
UPDATE STATISTICS dbo.r_GOperD
UPDATE STATISTICS dbo.r_GOperFC
UPDATE STATISTICS dbo.r_GOperFD
UPDATE STATISTICS dbo.r_GOpers
UPDATE STATISTICS dbo.r_GOpers_B1
UPDATE STATISTICS dbo.r_GOpers_B2
UPDATE STATISTICS dbo.r_GOpers_B3
UPDATE STATISTICS dbo.r_GOpers_P
UPDATE STATISTICS dbo.r_GVols
UPDATE STATISTICS dbo.r_GVols_B
UPDATE STATISTICS dbo.r_Holidays
UPDATE STATISTICS dbo.r_Ihecs
UPDATE STATISTICS dbo.r_Lengs
UPDATE STATISTICS dbo.r_LogOpers
UPDATE STATISTICS dbo.r_NormMH
UPDATE STATISTICS dbo.r_Norms
UPDATE STATISTICS dbo.r_NPostC
UPDATE STATISTICS dbo.r_NPosts
UPDATE STATISTICS dbo.r_NSubs
UPDATE STATISTICS dbo.r_Opers
UPDATE STATISTICS dbo.r_Ours
UPDATE STATISTICS dbo.r_Ours_B1
UPDATE STATISTICS dbo.r_Ours_B2
UPDATE STATISTICS dbo.r_Ours_C
UPDATE STATISTICS dbo.r_Ours_E
UPDATE STATISTICS dbo.r_Ours_N
UPDATE STATISTICS dbo.r_Ours_P
UPDATE STATISTICS dbo.r_Ours_S
UPDATE STATISTICS dbo.r_Ours_T1
UPDATE STATISTICS dbo.r_Ours_T2
UPDATE STATISTICS dbo.r_OursAC
UPDATE STATISTICS dbo.r_OursCC
UPDATE STATISTICS dbo.r_PayTypeCats
UPDATE STATISTICS dbo.r_PayTypes
UPDATE STATISTICS dbo.r_PLs
UPDATE STATISTICS dbo.r_PostC
UPDATE STATISTICS dbo.r_PostMC
UPDATE STATISTICS dbo.r_Posts
UPDATE STATISTICS dbo.r_Prevs
UPDATE STATISTICS dbo.r_ProdA
UPDATE STATISTICS dbo.r_ProdAC
UPDATE STATISTICS dbo.r_ProdBG
UPDATE STATISTICS dbo.r_ProdC
UPDATE STATISTICS dbo.r_ProdCV
UPDATE STATISTICS dbo.r_ProdEC
UPDATE STATISTICS dbo.r_ProdG
UPDATE STATISTICS dbo.r_ProdG1
UPDATE STATISTICS dbo.r_ProdG2
UPDATE STATISTICS dbo.r_ProdG3
UPDATE STATISTICS dbo.r_ProdMA
UPDATE STATISTICS dbo.r_ProdMC
UPDATE STATISTICS dbo.r_ProdME
UPDATE STATISTICS dbo.r_ProdMP
UPDATE STATISTICS dbo.r_ProdMPCh
UPDATE STATISTICS dbo.r_ProdMQ
UPDATE STATISTICS dbo.r_ProdMQ_T
UPDATE STATISTICS dbo.r_ProdMS
UPDATE STATISTICS dbo.r_ProdMSE
UPDATE STATISTICS dbo.r_Prods
UPDATE STATISTICS dbo.r_Prods_R

UPDATE STATISTICS dbo.r_QuesMA
UPDATE STATISTICS dbo.r_Quess
UPDATE STATISTICS dbo.r_RCards
UPDATE STATISTICS dbo.r_Secs
UPDATE STATISTICS dbo.r_Secs_T
UPDATE STATISTICS dbo.r_ShedMD
UPDATE STATISTICS dbo.r_ShedMS
UPDATE STATISTICS dbo.r_Sheds
UPDATE STATISTICS dbo.r_SLoyals
UPDATE STATISTICS dbo.r_SLoyalV
UPDATE STATISTICS dbo.r_StockGs
UPDATE STATISTICS dbo.r_Stocks
UPDATE STATISTICS dbo.r_Stocks_B1
UPDATE STATISTICS dbo.r_Stocks_B2
UPDATE STATISTICS dbo.r_Stocks_C
UPDATE STATISTICS dbo.r_Stocks_E1
UPDATE STATISTICS dbo.r_Stocks_E2
UPDATE STATISTICS dbo.r_Stocks_S1
UPDATE STATISTICS dbo.r_Stocks_S2
UPDATE STATISTICS dbo.r_Stocks_T1
UPDATE STATISTICS dbo.r_Stocks_T2
UPDATE STATISTICS dbo.r_Subs
UPDATE STATISTICS dbo.r_Users
UPDATE STATISTICS dbo.r_WPrefs
UPDATE STATISTICS dbo.r_WrkTypes
UPDATE STATISTICS dbo.r_WTSigns
UPDATE STATISTICS dbo.r_WWeeks
UPDATE STATISTICS dbo.s__BEOrd
UPDATE STATISTICS dbo.s__BIOrd
UPDATE STATISTICS dbo.s__BPOrd
UPDATE STATISTICS dbo.s__BProd
UPDATE STATISTICS dbo.s_Acc
UPDATE STATISTICS dbo.s_AccD
UPDATE STATISTICS dbo.s_Cos
UPDATE STATISTICS dbo.s_CosD
UPDATE STATISTICS dbo.s_CRet
UPDATE STATISTICS dbo.s_CRetD
UPDATE STATISTICS dbo.s_Cst
UPDATE STATISTICS dbo.s_CstD
UPDATE STATISTICS dbo.s_CstPG
UPDATE STATISTICS dbo.s_Dis
UPDATE STATISTICS dbo.s_DisD
UPDATE STATISTICS dbo.s_DisDD
UPDATE STATISTICS dbo.s_EOExp
UPDATE STATISTICS dbo.s_EOExpD
UPDATE STATISTICS dbo.s_EOExpDD
UPDATE STATISTICS dbo.s_EORec
UPDATE STATISTICS dbo.s_EORecD
UPDATE STATISTICS dbo.s_Epp
UPDATE STATISTICS dbo.s_EppD
UPDATE STATISTICS dbo.s_EppPA
UPDATE STATISTICS dbo.s_EppPB
UPDATE STATISTICS dbo.s_EppPC
UPDATE STATISTICS dbo.s_EppPG
UPDATE STATISTICS dbo.s_EppPO
UPDATE STATISTICS dbo.s_EppPR
UPDATE STATISTICS dbo.s_Est
UPDATE STATISTICS dbo.s_EstD
UPDATE STATISTICS dbo.s_Exc
UPDATE STATISTICS dbo.s_ExcD
UPDATE STATISTICS dbo.s_Exp
UPDATE STATISTICS dbo.s_ExpD
UPDATE STATISTICS dbo.s_ExpPA
UPDATE STATISTICS dbo.s_ExpPB
UPDATE STATISTICS dbo.s_ExpPC
UPDATE STATISTICS dbo.s_ExpPG
UPDATE STATISTICS dbo.s_ExpPO
UPDATE STATISTICS dbo.s_ExpPR
UPDATE STATISTICS dbo.s_Inv
UPDATE STATISTICS dbo.s_InvD
UPDATE STATISTICS dbo.s_InvPA
UPDATE STATISTICS dbo.s_InvPB
UPDATE STATISTICS dbo.s_InvPC
UPDATE STATISTICS dbo.s_InvPG
UPDATE STATISTICS dbo.s_InvPO
UPDATE STATISTICS dbo.s_InvPR
UPDATE STATISTICS dbo.s_IOExp
UPDATE STATISTICS dbo.s_IOExpD
UPDATE STATISTICS dbo.s_IORec
UPDATE STATISTICS dbo.s_IORecD
UPDATE STATISTICS dbo.s_Mon
UPDATE STATISTICS dbo.s_MonA
UPDATE STATISTICS dbo.s_MonD
UPDATE STATISTICS dbo.s_PInP
UPDATE STATISTICS dbo.s_PInP_S
UPDATE STATISTICS dbo.s_PInPCh
UPDATE STATISTICS dbo.s_Rec
UPDATE STATISTICS dbo.s_RecD
UPDATE STATISTICS dbo.s_RecPA
UPDATE STATISTICS dbo.s_RecPB
UPDATE STATISTICS dbo.s_RecPC
UPDATE STATISTICS dbo.s_RecPG
UPDATE STATISTICS dbo.s_RecPO
UPDATE STATISTICS dbo.s_RecPR
UPDATE STATISTICS dbo.s_Rem
UPDATE STATISTICS dbo.s_RemD
UPDATE STATISTICS dbo.s_RemDE
UPDATE STATISTICS dbo.s_Remx
UPDATE STATISTICS dbo.s_Ret
UPDATE STATISTICS dbo.s_RetD
UPDATE STATISTICS dbo.s_RetPA
UPDATE STATISTICS dbo.s_RetPB
UPDATE STATISTICS dbo.s_RetPC
UPDATE STATISTICS dbo.s_RetPO
UPDATE STATISTICS dbo.s_SExp
UPDATE STATISTICS dbo.s_SExpA
UPDATE STATISTICS dbo.s_SExpD
UPDATE STATISTICS dbo.s_SExpE
UPDATE STATISTICS dbo.s_SExpM
UPDATE STATISTICS dbo.s_SPExp
UPDATE STATISTICS dbo.s_SPExpA
UPDATE STATISTICS dbo.s_SPExpD
UPDATE STATISTICS dbo.s_SPExpE
UPDATE STATISTICS dbo.s_SPExpM
UPDATE STATISTICS dbo.s_SPRec
UPDATE STATISTICS dbo.s_SPRecA
UPDATE STATISTICS dbo.s_SPRecD
UPDATE STATISTICS dbo.s_SPRecE
UPDATE STATISTICS dbo.s_SPRecM
UPDATE STATISTICS dbo.s_SRec
UPDATE STATISTICS dbo.s_SRecA
UPDATE STATISTICS dbo.s_SRecD
UPDATE STATISTICS dbo.s_SRecE
UPDATE STATISTICS dbo.s_SRecM
UPDATE STATISTICS dbo.s_Ven
UPDATE STATISTICS dbo.s_VenA
UPDATE STATISTICS dbo.s_VenD
UPDATE STATISTICS dbo.s_zInP
UPDATE STATISTICS dbo.t__BCR
UPDATE STATISTICS dbo.t__BDay
UPDATE STATISTICS dbo.t__BEOrd
UPDATE STATISTICS dbo.t__BIOrd
UPDATE STATISTICS dbo.t__BPOrd
UPDATE STATISTICS dbo.t__BProd
UPDATE STATISTICS dbo.t_Acc
UPDATE STATISTICS dbo.t_AccD
UPDATE STATISTICS dbo.t_Cos
UPDATE STATISTICS dbo.t_CosD
UPDATE STATISTICS dbo.t_CRet
UPDATE STATISTICS dbo.t_CRetD
UPDATE STATISTICS dbo.t_CRRet
UPDATE STATISTICS dbo.t_CRRetD
UPDATE STATISTICS dbo.t_CRSale
UPDATE STATISTICS dbo.t_CRSaleD
UPDATE STATISTICS dbo.t_Cst
UPDATE STATISTICS dbo.t_CstD
UPDATE STATISTICS dbo.t_CstPG
UPDATE STATISTICS dbo.t_Dis
UPDATE STATISTICS dbo.t_DisD
UPDATE STATISTICS dbo.t_DisDD
UPDATE STATISTICS dbo.t_EOExp
UPDATE STATISTICS dbo.t_EOExpD
UPDATE STATISTICS dbo.t_EOExpDD
UPDATE STATISTICS dbo.t_EORec
UPDATE STATISTICS dbo.t_EORecD
UPDATE STATISTICS dbo.t_Epp
UPDATE STATISTICS dbo.t_EppD
UPDATE STATISTICS dbo.t_EppPA
UPDATE STATISTICS dbo.t_EppPB
UPDATE STATISTICS dbo.t_EppPC
UPDATE STATISTICS dbo.t_EppPG
UPDATE STATISTICS dbo.t_EppPO
UPDATE STATISTICS dbo.t_EppPR
UPDATE STATISTICS dbo.t_Est
UPDATE STATISTICS dbo.t_EstD
UPDATE STATISTICS dbo.t_Exc
UPDATE STATISTICS dbo.t_ExcD
UPDATE STATISTICS dbo.t_Exp
UPDATE STATISTICS dbo.t_ExpD
UPDATE STATISTICS dbo.t_ExpPA
UPDATE STATISTICS dbo.t_ExpPB
UPDATE STATISTICS dbo.t_ExpPC
UPDATE STATISTICS dbo.t_ExpPG
UPDATE STATISTICS dbo.t_ExpPO
UPDATE STATISTICS dbo.t_ExpPR
UPDATE STATISTICS dbo.t_IOExp
UPDATE STATISTICS dbo.t_IOExpD
UPDATE STATISTICS dbo.t_IORec
UPDATE STATISTICS dbo.t_IORecD
UPDATE STATISTICS dbo.t_MExp
UPDATE STATISTICS dbo.t_MRec
UPDATE STATISTICS dbo.t_PInP
UPDATE STATISTICS dbo.t_PInP_T
UPDATE STATISTICS dbo.t_PInPCh
UPDATE STATISTICS dbo.t_Rec
UPDATE STATISTICS dbo.t_RecD
UPDATE STATISTICS dbo.t_RecPA
UPDATE STATISTICS dbo.t_RecPB
UPDATE STATISTICS dbo.t_RecPC
UPDATE STATISTICS dbo.t_RecPG
UPDATE STATISTICS dbo.t_RecPO
UPDATE STATISTICS dbo.t_RecPR
UPDATE STATISTICS dbo.t_Rem
UPDATE STATISTICS dbo.t_RemD
UPDATE STATISTICS dbo.t_RemDE
UPDATE STATISTICS dbo.t_Remx
UPDATE STATISTICS dbo.t_Ret
UPDATE STATISTICS dbo.t_RetD
UPDATE STATISTICS dbo.t_RetPA
UPDATE STATISTICS dbo.t_RetPB
UPDATE STATISTICS dbo.t_RetPC
UPDATE STATISTICS dbo.t_RetPO
UPDATE STATISTICS dbo.t_Sale
UPDATE STATISTICS dbo.t_SaleC
UPDATE STATISTICS dbo.t_SaleD
UPDATE STATISTICS dbo.t_SEst
UPDATE STATISTICS dbo.t_SEstD
UPDATE STATISTICS dbo.t_SExp
UPDATE STATISTICS dbo.t_SExpA
UPDATE STATISTICS dbo.t_SExpD
UPDATE STATISTICS dbo.t_SExpE
UPDATE STATISTICS dbo.t_SExpM
UPDATE STATISTICS dbo.t_SPExp
UPDATE STATISTICS dbo.t_SPExpA
UPDATE STATISTICS dbo.t_SPExpD
UPDATE STATISTICS dbo.t_SPExpE
UPDATE STATISTICS dbo.t_SPExpM
UPDATE STATISTICS dbo.t_SPRec
UPDATE STATISTICS dbo.t_SPRecA
UPDATE STATISTICS dbo.t_SPRecD
UPDATE STATISTICS dbo.t_SPRecE
UPDATE STATISTICS dbo.t_SPRecM
UPDATE STATISTICS dbo.t_SRec
UPDATE STATISTICS dbo.t_SRecA
UPDATE STATISTICS dbo.t_SRecD
UPDATE STATISTICS dbo.t_SRecE
UPDATE STATISTICS dbo.t_SRecM
UPDATE STATISTICS dbo.t_STemp
UPDATE STATISTICS dbo.t_Ven
UPDATE STATISTICS dbo.t_VenA
UPDATE STATISTICS dbo.t_VenD
UPDATE STATISTICS dbo.t_xAnn
UPDATE STATISTICS dbo.t_xGen
UPDATE STATISTICS dbo.t_xOper
UPDATE STATISTICS dbo.t_xOperD
UPDATE STATISTICS dbo.t_xRQty
UPDATE STATISTICS dbo.t_zInP
UPDATE STATISTICS dbo.v_Databases
UPDATE STATISTICS dbo.v_Fields
UPDATE STATISTICS dbo.v_Formulas
UPDATE STATISTICS dbo.v_Joins
UPDATE STATISTICS dbo.v_MapSG
UPDATE STATISTICS dbo.v_Params
UPDATE STATISTICS dbo.v_RepGrs
UPDATE STATISTICS dbo.v_Replace
UPDATE STATISTICS dbo.v_Reps
UPDATE STATISTICS dbo.v_RepUsers
UPDATE STATISTICS dbo.v_SourceGrs
UPDATE STATISTICS dbo.v_Sources
UPDATE STATISTICS dbo.v_Tables
UPDATE STATISTICS dbo.v_UFields
UPDATE STATISTICS dbo.v_UParams
UPDATE STATISTICS dbo.v_UReps

UPDATE STATISTICS dbo.x_DimG
UPDATE STATISTICS dbo.x_Dims
UPDATE STATISTICS dbo.x_Docs
UPDATE STATISTICS dbo.x_Fields
UPDATE STATISTICS dbo.x_Opers
UPDATE STATISTICS dbo.x_RepG
UPDATE STATISTICS dbo.x_RepNotes
UPDATE STATISTICS dbo.x_Reps
UPDATE STATISTICS dbo.x_RWTables
UPDATE STATISTICS dbo.x_SCDims
UPDATE STATISTICS dbo.x_Vars
UPDATE STATISTICS dbo.z_AccDefDocs
UPDATE STATISTICS dbo.z_AccDefs
UPDATE STATISTICS dbo.z_AccDefTables
UPDATE STATISTICS dbo.z_BarMask
UPDATE STATISTICS dbo.z_Contracts
UPDATE STATISTICS dbo.z_DocDF
UPDATE STATISTICS dbo.z_DocList
UPDATE STATISTICS dbo.z_DocList_B1
UPDATE STATISTICS dbo.z_DocList_B2
UPDATE STATISTICS dbo.z_DocList_C
UPDATE STATISTICS dbo.z_DocList_S
UPDATE STATISTICS dbo.z_DocList_T
UPDATE STATISTICS dbo.z_DocListMG
UPDATE STATISTICS dbo.z_FRUDFR
UPDATE STATISTICS dbo.z_FRUDFRD
UPDATE STATISTICS dbo.z_FRUDFs
UPDATE STATISTICS dbo.z_ProdMC
UPDATE STATISTICS dbo.z_ProdMP
UPDATE STATISTICS dbo.z_RelFields
UPDATE STATISTICS dbo.z_Rels
UPDATE STATISTICS dbo.z_RoleDocs
UPDATE STATISTICS dbo.z_Roles
UPDATE STATISTICS dbo.z_RoleTables
UPDATE STATISTICS dbo.z_RoleUsers
UPDATE STATISTICS dbo.z_Sys
UPDATE STATISTICS dbo.z_Sys2
UPDATE STATISTICS dbo.z_SysApps
UPDATE STATISTICS dbo.z_SysVers
UPDATE STATISTICS dbo.z_TableJoinA
UPDATE STATISTICS dbo.z_TableJoinB
UPDATE STATISTICS dbo.z_UDB
UPDATE STATISTICS dbo.z_UDC
UPDATE STATISTICS dbo.z_UDE
UPDATE STATISTICS dbo.z_UDP
UPDATE STATISTICS dbo.z_UDS
UPDATE STATISTICS dbo.z_UDT
UPDATE STATISTICS dbo.z_UDV
UPDATE STATISTICS dbo.z_UDZ
UPDATE STATISTICS dbo.z_UserDocs
UPDATE STATISTICS dbo.z_UserOpts
UPDATE STATISTICS dbo.z_UserTables
UPDATE STATISTICS dbo.z_UserVars
UPDATE STATISTICS dbo.z_Vars
UPDATE STATISTICS dbo.z_WCopy
UPDATE STATISTICS dbo.z_WCopyD
UPDATE STATISTICS dbo.z_WCopyDF
UPDATE STATISTICS dbo.z_WCopyDV
UPDATE STATISTICS dbo.z_WCopyF
UPDATE STATISTICS dbo.z_WCopyFF
UPDATE STATISTICS dbo.z_WCopyFUF
UPDATE STATISTICS dbo.z_WCopyFV
UPDATE STATISTICS dbo.z_WCopyFVUF
UPDATE STATISTICS dbo.z_WCopyP
UPDATE STATISTICS dbo.z_WCopyT
UPDATE STATISTICS dbo.z_WCopyU
UPDATE STATISTICS dbo.z_WCopyUV

PRINT 'Производится сжатие базы данных. Пожалуйста подождите...'
DBCC SHRINKDATABASE (OTData_M6)

PRINT ''
PRINT '****************************************************************************************'
PRINT '*                   ГОТОВО!!! СПАСИБО ЗА ПЛОДОТВОРНОЕ СОТРУДНИЧЕСТВО.                  *'
PRINT '*               Со всеми вопросами и предложениями обращайтесь в IT отдел.             *'
PRINT '****************************************************************************************'
*/