--use otdata74
/*TRUNCATE TABLE	_Ch

TRUNCATE TABLE r_prodMP
TRUNCATE TABLE	r_ProdMPCh
TRUNCATE TABLE	r_ProdMQ
TRUNCATE TABLE	r_Prods
TRUNCATE TABLE	r_Prods_R

TRUNCATE TABLE	t_Sale
TRUNCATE TABLE	t_SaleD
TRUNCATE TABLE	t_Epp
TRUNCATE TABLE	t_EppD

TRUNCATE TABLE	t_PInP
TRUNCATE TABLE	t_PInP_T
TRUNCATE TABLE	t_PInPCh
TRUNCATE TABLE	t_Rec
TRUNCATE TABLE	t_RecD

TRUNCATE TABLE	t_Rem

TRUNCATE TABLE	t_ven
TRUNCATE TABLE	t_venA
TRUNCATE TABLE	t_venD
 */